; Tilesets indexes (see data/tilesets.asm)
	const_def 1
	const TILESET_JOHTO                ; 01
	const TILESET_JOHTO_MODERN         ; 02
	const TILESET_KANTO                ; 03
	const TILESET_BATTLE_TOWER_OUTSIDE ; 04
	const TILESET_HOUSE                ; 05
	const TILESET_PLAYERS_HOUSE        ; 06
	const TILESET_POKECENTER           ; 07
	const TILESET_GATE                 ; 08
	const TILESET_PORT                 ; 09
	const TILESET_LAB                  ; 0a
	const TILESET_FACILITY             ; 0b
	const TILESET_MART                 ; 0c
	const TILESET_MANSION              ; 0d
	const TILESET_GAME_CORNER          ; 0e
	const TILESET_ELITE_FOUR_ROOM      ; 0f
	const TILESET_TRADITIONAL_HOUSE    ; 10
	const TILESET_TRAIN_STATION        ; 11
	const TILESET_CHAMPIONS_ROOM       ; 12
	const TILESET_LIGHTHOUSE           ; 13
	const TILESET_PLAYERS_ROOM         ; 14
	const TILESET_POKECOM_CENTER       ; 15
	const TILESET_BATTLE_TOWER         ; 16
	const TILESET_TOWER                ; 17
	const TILESET_CAVE                 ; 18
	const TILESET_PARK                 ; 19
	const TILESET_RUINS_OF_ALPH        ; 1a
	const TILESET_RADIO_TOWER          ; 1b
	const TILESET_UNDERGROUND          ; 1c
	const TILESET_ICE_PATH             ; 1d
	const TILESET_DARK_CAVE            ; 1e
	const TILESET_FOREST               ; 1f
	const TILESET_BETA_WORD_ROOM       ; 20
	const TILESET_HO_OH_WORD_ROOM      ; 21
	const TILESET_KABUTO_WORD_ROOM     ; 22
	const TILESET_OMANYTE_WORD_ROOM    ; 23
	const TILESET_AERODACTYL_WORD_ROOM ; 24
; --- Polished Crystal imported tilesets (auto-generated) ---
	const TILESET_POLISHED_BATTLE_FACTORY_A
	const TILESET_POLISHED_BATTLE_FACTORY_B
	const TILESET_POLISHED_BATTLE_TOWER_INSIDE
	const TILESET_POLISHED_BATTLE_TOWER_OUTSIDE
	const TILESET_POLISHED_CAVE
	const TILESET_POLISHED_CHAMPIONS_ROOM
	const TILESET_POLISHED_HOME_DECOR_STORE
	const TILESET_POLISHED_ECRUTEAK_SHRINE
	const TILESET_POLISHED_FACILITY
	const TILESET_POLISHED_FARAWAY_ISLAND
	const TILESET_POLISHED_FOREST_A
	const TILESET_POLISHED_GAME_CORNER
	const TILESET_POLISHED_GATE
	const TILESET_POLISHED_GYM_A
	const TILESET_POLISHED_GYM_B
	const TILESET_POLISHED_HIDDEN_GROTTO
	const TILESET_POLISHED_HIDEOUT
	const TILESET_POLISHED_HOTEL
	const TILESET_POLISHED_ICE_PATH
	const TILESET_POLISHED_INDIGO_PLATEAU
	const TILESET_POLISHED_JOHTO_ANCIENT
	const TILESET_POLISHED_JOHTO_COAST_A
	const TILESET_POLISHED_JOHTO_COAST_B
	const TILESET_POLISHED_JOHTO_HOUSE_A
	const TILESET_POLISHED_JOHTO_MODERN_A
	const TILESET_POLISHED_JOHTO_OUTLANDS_A
	const TILESET_POLISHED_JOHTO_TRADITIONAL_A
	const TILESET_POLISHED_JOHTO_TRADITIONAL_B
	const TILESET_POLISHED_KANTO_A
	const TILESET_POLISHED_KANTO_GYM_A
	const TILESET_POLISHED_KANTO_GYM_B
	const TILESET_POLISHED_KANTO_HOUSE_A
	const TILESET_POLISHED_KANTO_HOUSE_B
	const TILESET_POLISHED_KANTO_NORTH
	const TILESET_POLISHED_LAB_A
	const TILESET_POLISHED_LIGHTHOUSE
	const TILESET_POLISHED_MAGNET_TRAIN
	const TILESET_POLISHED_CELADON_MANSION
	const TILESET_POLISHED_MART
	const TILESET_POLISHED_MUSEUM_A
	const TILESET_POLISHED_MUSEUM_B
	const TILESET_POLISHED_PARK
	const TILESET_POLISHED_PEAKS
	const TILESET_POLISHED_POKECENTER
	const TILESET_POLISHED_POKECOM_CENTER_A
	const TILESET_POLISHED_POKEMON_MANSION
	const TILESET_POLISHED_PORT
	const TILESET_POLISHED_QUIET_CAVE
	const TILESET_POLISHED_RADIO_TOWER
	const TILESET_POLISHED_RUINS_OF_ALPH
	const TILESET_POLISHED_SAFARI_ZONE
	const TILESET_POLISHED_SHAMOUTI_ISLAND_A
	const TILESET_POLISHED_SHAMOUTI_ISLAND_B
	const TILESET_POLISHED_SNOWTOP_MOUNTAIN_A
	const TILESET_POLISHED_SPROUT_TOWER_A
	const TILESET_POLISHED_SPROUT_TOWER_B
	const TILESET_POLISHED_TRADITIONAL_HOUSE
	const TILESET_POLISHED_TUNNEL
	const TILESET_POLISHED_UNDERGROUND
	const TILESET_POLISHED_VALENCIA_ISLAND
NUM_TILESETS EQU const_value

; bg palette values (see gfx/tilesets/*_palette_map.asm)
; TilesetBGPalette indexes (see gfx/tilesets/bg_tiles.pal)
	const_def
	const PAL_BG_GRAY   ; 0
	const PAL_BG_RED    ; 1
	const PAL_BG_GREEN  ; 2
	const PAL_BG_WATER  ; 3
	const PAL_BG_YELLOW ; 4
	const PAL_BG_BROWN  ; 5
	const PAL_BG_ROOF   ; 6
	const PAL_BG_TEXT   ; 7
