Cries:
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Fearow
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Sunflora
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Dunsparce
	dba Cry_Donphan
	dba Cry_Shroomish
	dba Cry_Breloom
	dba Cry_Ralts
	dba Cry_Kirlia
	dba Cry_Gallade
	dba Cry_Sneasler

; imported from Polished Coral
; Hoenn (gen 3)
	dba Cry_Aron
	dba Cry_Lairon
	dba Cry_Aggron
	dba Cry_Numel
	dba Cry_Camerupt
	dba Cry_Swablu
	dba Cry_Altaria
	dba Cry_Snorunt
; Sinnoh (gen 4)
	dba Cry_Drifloon
	dba Cry_Drifblim
	dba Cry_Buneary
	dba Cry_Lopunny
	dba Cry_Snover
	dba Cry_Abomasnow
	dba Cry_Froslass
; Unova (gen 5)
	dba Cry_Drilbur
	dba Cry_Excadrill
	dba Cry_Venipede
	dba Cry_Whirlipede
	dba Cry_Scolipede
	dba Cry_Scraggy
	dba Cry_Scrafty
	dba Cry_Joltik
	dba Cry_Galvantula
	dba Cry_Litwick
	dba Cry_Lampent
	dba Cry_Chandelure
	dba Cry_Larvesta
	dba Cry_Volcarona
; Kalos (gen 6)
	dba Cry_Noibat
	dba Cry_Noivern
; Galar (gen 8)
	dba Cry_Dreepy
	dba Cry_Drakloak
	dba Cry_Dragapult
