AnimationPointers:
	dba BulbasaurAnimation
	dba IvysaurAnimation
	dba VenusaurAnimation
	dba CharmanderAnimation
	dba CharmeleonAnimation
	dba CharizardAnimation
	dba SquirtleAnimation
	dba WartortleAnimation
	dba BlastoiseAnimation
	dba CaterpieAnimation
	dba MetapodAnimation
	dba ButterfreeAnimation
	dba WeedleAnimation
	dba KakunaAnimation
	dba BeedrillAnimation
	dba PidgeyAnimation
	dba PidgeottoAnimation
	dba PidgeotAnimation
	dba RattataAnimation
	dba RaticateAnimation
	dba SpearowAnimation
	dba FearowAnimation
	dba EkansAnimation
	dba ArbokAnimation
	dba PikachuAnimation
	dba RaichuAnimation
	dba SandshrewAnimation
	dba SandslashAnimation
	dba NidoranFAnimation
	dba NidorinaAnimation
	dba NidoqueenAnimation
	dba NidoranMAnimation
	dba NidorinoAnimation
	dba NidokingAnimation
	dba ClefairyAnimation
	dba ClefableAnimation
	dba VulpixAnimation
	dba NinetalesAnimation
	dba JigglypuffAnimation
	dba WigglytuffAnimation
	dba ZubatAnimation
	dba GolbatAnimation
	dba OddishAnimation
	dba GloomAnimation
	dba VileplumeAnimation
	dba ParasAnimation
	dba ParasectAnimation
	dba VenonatAnimation
	dba VenomothAnimation
	dba DiglettAnimation
	dba DugtrioAnimation
	dba MeowthAnimation
	dba PersianAnimation
	dba PsyduckAnimation
	dba GolduckAnimation
	dba MankeyAnimation
	dba PrimeapeAnimation
	dba GrowlitheAnimation
	dba ArcanineAnimation
	dba PoliwagAnimation
	dba PoliwhirlAnimation
	dba PoliwrathAnimation
	dba AbraAnimation
	dba KadabraAnimation
	dba AlakazamAnimation
	dba MachopAnimation
	dba MachokeAnimation
	dba MachampAnimation
	dba BellsproutAnimation
	dba WeepinbellAnimation
	dba VictreebelAnimation
	dba TentacoolAnimation
	dba TentacruelAnimation
	dba GeodudeAnimation
	dba GravelerAnimation
	dba GolemAnimation
	dba PonytaAnimation
	dba RapidashAnimation
	dba SlowpokeAnimation
	dba SlowbroAnimation
	dba MagnemiteAnimation
	dba MagnetonAnimation
	dba FarfetchDAnimation
	dba DoduoAnimation
	dba DodrioAnimation
	dba SeelAnimation
	dba DewgongAnimation
	dba GrimerAnimation
	dba MukAnimation
	dba ShellderAnimation
	dba CloysterAnimation
	dba GastlyAnimation
	dba HaunterAnimation
	dba GengarAnimation
	dba OnixAnimation
	dba DrowzeeAnimation
	dba HypnoAnimation
	dba KrabbyAnimation
	dba KinglerAnimation
	dba VoltorbAnimation
	dba ElectrodeAnimation
	dba ExeggcuteAnimation
	dba ExeggutorAnimation
	dba CuboneAnimation
	dba MarowakAnimation
	dba HitmonleeAnimation
	dba HitmonchanAnimation
	dba LickitungAnimation
	dba KoffingAnimation
	dba WeezingAnimation
	dba RhyhornAnimation
	dba RhydonAnimation
	dba ChanseyAnimation
	dba TangelaAnimation
	dba KangaskhanAnimation
	dba HorseaAnimation
	dba SeadraAnimation
	dba GoldeenAnimation
	dba SeakingAnimation
	dba StaryuAnimation
	dba StarmieAnimation
	dba MrMimeAnimation
	dba ScytherAnimation
	dba JynxAnimation
	dba ElectabuzzAnimation
	dba MagmarAnimation
	dba PinsirAnimation
	dba TaurosAnimation
	dba MagikarpAnimation
	dba GyaradosAnimation
	dba LaprasAnimation
	dba DittoAnimation
	dba EeveeAnimation
	dba VaporeonAnimation
	dba JolteonAnimation
	dba FlareonAnimation
	dba PorygonAnimation
	dba OmanyteAnimation
	dba OmastarAnimation
	dba KabutoAnimation
	dba KabutopsAnimation
	dba AerodactylAnimation
	dba SnorlaxAnimation
	dba ArticunoAnimation
	dba ZapdosAnimation
	dba MoltresAnimation
	dba DratiniAnimation
	dba DragonairAnimation
	dba DragoniteAnimation
	dba MewtwoAnimation
	dba MewAnimation
	dba ChikoritaAnimation
	dba BayleefAnimation
	dba MeganiumAnimation
	dba CyndaquilAnimation
	dba QuilavaAnimation
	dba TyphlosionAnimation
	dba TotodileAnimation
	dba CroconawAnimation
	dba FeraligatrAnimation
	dba SentretAnimation
	dba FurretAnimation
	dba HoothootAnimation
	dba NoctowlAnimation
	dba LedybaAnimation
	dba LedianAnimation
	dba SpinarakAnimation
	dba AriadosAnimation
	dba CrobatAnimation
	dba ChinchouAnimation
	dba LanturnAnimation
	dba PichuAnimation
	dba CleffaAnimation
	dba IgglybuffAnimation
	dba TogepiAnimation
	dba TogeticAnimation
	dba NatuAnimation
	dba XatuAnimation
	dba MareepAnimation
	dba FlaaffyAnimation
	dba AmpharosAnimation
	dba BellossomAnimation
	dba MarillAnimation
	dba AzumarillAnimation
	dba SudowoodoAnimation
	dba PolitoedAnimation
	dba HoppipAnimation
	dba SkiploomAnimation
	dba JumpluffAnimation
	dba AipomAnimation
	dba SunkernAnimation
	dba SunfloraAnimation
	dba YanmaAnimation
	dba WooperAnimation
	dba QuagsireAnimation
	dba EspeonAnimation
	dba UmbreonAnimation
	dba MurkrowAnimation
	dba SlowkingAnimation
	dba MisdreavusAnimation
	dba UnownAnimation
	dba WobbuffetAnimation
	dba GirafarigAnimation
	dba PinecoAnimation
	dba ForretressAnimation
	dba DunsparceAnimation
	dba GligarAnimation
	dba SteelixAnimation
	dba SnubbullAnimation
	dba GranbullAnimation
	dba QwilfishAnimation
	dba ScizorAnimation
	dba ShuckleAnimation
	dba HeracrossAnimation
	dba SneaselAnimation
	dba TeddiursaAnimation
	dba UrsaringAnimation
	dba SlugmaAnimation
	dba MagcargoAnimation
	dba SwinubAnimation
	dba PiloswineAnimation
	dba CorsolaAnimation
	dba RemoraidAnimation
	dba OctilleryAnimation
	dba DelibirdAnimation
	dba MantineAnimation
	dba SkarmoryAnimation
	dba HoundourAnimation
	dba HoundoomAnimation
	dba KingdraAnimation
	dba PhanpyAnimation
	dba DonphanAnimation
	dba Porygon2Animation
	dba StantlerAnimation
	dba SmeargleAnimation
	dba TyrogueAnimation
	dba HitmontopAnimation
	dba SmoochumAnimation
	dba ElekidAnimation
	dba MagbyAnimation
	dba MiltankAnimation
	dba BlisseyAnimation
	dba RaikouAnimation
	dba EnteiAnimation
	dba SuicuneAnimation
	dba LarvitarAnimation
	dba PupitarAnimation
	dba TyranitarAnimation
	dba LugiaAnimation
	dba HoOhAnimation
	dba CelebiAnimation
	dba CharmanderCloneAnimation
	dba CharmeleonCloneAnimation
	dba CharizardCloneAnimation
	dba SquirtleCloneAnimation
	dba WartortleCloneAnimation
	dba BlastoiseCloneAnimation
	dba BulbasaurCloneAnimation
	dba IvysaurCloneAnimation
	dba VenusaurCloneAnimation
	dba HonchkrowAnimation
	dba AmbipomAnimation
	dba AnnihilapeAnimation
	dba BagonAnimation
	dba ShelgonAnimation
	dba SalamenceAnimation
	dba DrunsparceAnimation
	dba ElectivireAnimation
	dba FarigirafAnimation
	dba RaltsAnimation
	dba KirliaAnimation
	dba GardevoirAnimation
	dba GalladeAnimation
	dba GlaceonAnimation
	dba LeafeonAnimation
	dba SylveonAnimation
	dba GliscorAnimation
	dba LickilickyAnimation
	dba MagmortarAnimation
	dba MagnezoneAnimation
	dba MamoswineAnimation
	dba MesmeriaAnimation
	dba MismagiusAnimation
	dba PorygonZAnimation
	dba RhyperiorAnimation
	dba VenipedeAnimation
	dba WhirlipedeAnimation
	dba ScolipedeAnimation
	dba TangrowthAnimation
	dba TogekissAnimation
	dba UrsalunaAnimation
	dba WeavileAnimation
	dba WyrdeerAnimation
	dba YanmegaAnimation
	dba LileepAnimation
	dba CradilyAnimation
	dba AnorithAnimation
	dba ArmaldoAnimation
	dba GolettAnimation
	dba GolurkAnimation
	dba DuskullAnimation
	dba DusclopsAnimation
	dba DusknoirAnimation
	dba TimburrAnimation
	dba GurdurrAnimation
	dba ConkeldurrAnimation
	dba LarvestaAnimation
	dba VolcaronaAnimation
	dba DeinoAnimation
	dba ZweilousAnimation
	dba HydreigonAnimation
	dba DreepyAnimation
	dba DrakloakAnimation
	dba DragapultAnimation
	dba ImpidimpAnimation
	dba MorgremAnimation
	dba GrimmsnarlAnimation
	dba TinkatinkAnimation
	dba TinkatuffAnimation
	dba TinkatonAnimation
	dba FrigibaxAnimation
	dba ArctibaxAnimation
	dba BaxcaliburAnimation
	dba CharcadetAnimation
	dba ArmarougeAnimation
	dba CeruledgeAnimation
	dba RookideeAnimation
	dba CorvisquireAnimation
	dba CorviknightAnimation
	dba SnoverAnimation
	dba AbomasnowAnimation
	dba SwabluAnimation
	dba AltariaAnimation
	dba ApplinAnimation
	dba DipplinAnimation
	dba AppletunAnimation
	dba FlappleAnimation
	dba HydrappleAnimation
	dba DuraludonAnimation
	dba ArchaludonAnimation
	dba ShroomishAnimation
	dba BreloomAnimation
	dba BunearyAnimation
	dba LopunnyAnimation
	dba NumelAnimation
	dba CameruptAnimation
	dba SizzlipedeAnimation
	dba CentiskorchAnimation
	dba GrubbinAnimation
	dba CharjabugAnimation
	dba VikavoltAnimation
	dba CroagunkAnimation
	dba ToxicroakAnimation
	dba DrifloonAnimation
	dba DrifblimAnimation
	dba DrilburAnimation
	dba ExcadrillAnimation
	dba KotoraAnimation
	dba RaitoraAnimation
	dba GorotoraAnimation
	dba FletchlingAnimation
	dba FletchinderAnimation
	dba TalonflameAnimation
	dba TrapinchAnimation
	dba VibravaAnimation
	dba FlygonAnimation
	dba SnoruntAnimation
	dba FroslassAnimation
	dba WimpodAnimation
	dba GolisopodAnimation
	dba SpoinkAnimation
	dba GrumpigAnimation
	dba PawniardAnimation
	dba BisharpAnimation
	dba KingambitAnimation
	dba LotadAnimation
	dba LombreAnimation
	dba LudicoloAnimation
	dba OverqwilAnimation
	dba ScraggyAnimation
	dba ScraftyAnimation
	dba SphealAnimation
	dba SealeoAnimation
	dba WalreinAnimation
	dba TeddiursabmAnimation
	dba UrsaringbmAnimation
	dba UrsalunabmAnimation
	dba AxewAnimation
	dba FraxureAnimation
	dba HaxorusAnimation
	dba CranidosAnimation
	dba RampardosAnimation
	dba ShieldonAnimation
	dba BastiodonAnimation
	dba CetoddleAnimation
	dba CetitanAnimation
	dba FeebasAnimation
	dba MiloticAnimation
	dba MimikyuAnimation
	dba CorsolaGalarianAnimation
	dba CursolaAnimation
	dba MrRimeAnimation
	dba SirfetchDAnimation
	dba RioluAnimation
	dba LucarioAnimation
	dba TyruntAnimation
	dba TyrantrumAnimation
	dba AmauraAnimation
	dba AurorusAnimation
	dba MunchlaxAnimation
	dba TorkoalAnimation
	dba RattataAlolanAnimation
	dba RaticateAlolanAnimation
	dba RaichuAlolanAnimation
	dba SandshrewAlolanAnimation
	dba SandslashAlolanAnimation
	dba VulpixAlolanAnimation
	dba NinetalesAlolanAnimation
	dba DiglettAlolanAnimation
	dba DugtrioAlolanAnimation
	dba MeowthAlolanAnimation
	dba PersianAlolanAnimation
	dba GeodudeAlolanAnimation
	dba GravelerAlolanAnimation
	dba GolemAlolanAnimation
	dba GrimerAlolanAnimation
	dba MukAlolanAnimation
	dba ExeggutorAlolanAnimation
	dba MarowakAlolanAnimation
	dba MeowthGalarianAnimation
	dba PerrserkerAnimation
	dba PonytaGalarianAnimation
	dba RapidashGalarianAnimation
	dba SlowpokeGalarianAnimation
	dba SlowbroGalarianAnimation
	dba SlowkingGalarianAnimation
	dba WeezingGalarianAnimation
	dba GrowlitheHisuianAnimation
	dba ArcanineHisuianAnimation
	dba VoltorbHisuianAnimation
	dba ElectrodeHisuianAnimation
	dba TyphlosionHisuianAnimation
	dba SneaselHisuianAnimation
	dba SneaslerAnimation
	dba WooperPaldeanAnimation
	dba ClodsireAnimation
	dba TaurosPaldeanFireAnimation
	dba TaurosPaldeanWaterAnimation
	dba WatuAnimation
	dba BounsweetAnimation
	dba SteeneeAnimation
	dba TsareenaAnimation
	dba AronAnimation
	dba LaironAnimation
	dba AggronAnimation
	dba KleavorAnimation
	dba GlimmetAnimation
	dba GlimmoraAnimation
	dba MareanieAnimation
	dba ToxapexAnimation
	dba ZangooseAnimation
	dba SeviperAnimation
	dba ShuppetAnimation
	dba BanetteAnimation
	dba ArchenAnimation
	dba ArcheopsAnimation
	dba TirtougaAnimation
	dba CarracostaAnimation
	dba LitwickAnimation
	dba LampentAnimation
	dba ChandelureAnimation
	dba JoltikAnimation
	dba GalvantulaAnimation
	dba MawileAnimation
	dba NoibatAnimation
	dba NoivernAnimation
	dba SalanditAnimation
	dba SalazzleAnimation
