BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw HonchkrowBitmasks
	dw AmbipomBitmasks
	dw AnnihilapeBitmasks
	dw BagonBitmasks
	dw DrunsparceBitmasks
	dw ElectivireBitmasks
	dw FarigirafBitmasks
	dw GardevoirBitmasks
	dw GlaceonBitmasks
	dw GliscorBitmasks
	dw KirliaBitmasks
	dw LeafeonBitmasks
	dw LickilickyBitmasks
	dw MagmortarBitmasks
	dw MagnezoneBitmasks
	dw MamoswineBitmasks
	dw MesmeriaBitmasks
	dw MismagiusBitmasks
	dw PorygonZBitmasks
	dw RaltsBitmasks
	dw RhyperiorBitmasks
	dw SalamenceBitmasks
	dw ScolipedeBitmasks
	dw ShelgonBitmasks
	dw TangrowthBitmasks
	dw TogekissBitmasks
	dw UrsalunaBitmasks
	dw VenipedeBitmasks
	dw WeavileBitmasks
	dw WhirlipedeBitmasks
	dw WyrdeerBitmasks
	dw YanmegaBitmasks
	dw LileepBitmasks
	dw CradilyBitmasks
	dw ArmaldoBitmasks
	dw GolettBitmasks
	dw GolurkBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw DeinoBitmasks
	dw ZweilousBitmasks
	dw HydreigonBitmasks
	dw DreepyBitmasks
	dw DrakloakBitmasks
	dw DragapultBitmasks
	dw ImpidimpBitmasks
	dw MorgremBitmasks
	dw GrimmsnarlBitmasks
	dw TinkatinkBitmasks
	dw TinkatuffBitmasks
	dw TinkatonBitmasks
	dw FrigibaxBitmasks
	dw ArctibaxBitmasks
	dw BaxcaliburBitmasks
	dw CharcadetBitmasks
	dw ArmarogueBitmasks
	dw CeruledgeBitmasks
	dw SylveonBitmasks
	dw RookideeBitmasks
	dw CorvisquireBitmasks
	dw CorviknightBitmasks
	dw AbomasnowBitmasks
	dw AltariaBitmasks
	dw AnorithBitmasks
	dw AppletunBitmasks
	dw ApplinBitmasks
	dw ArchaludonBitmasks
	dw BreloomBitmasks
	dw BunearyBitmasks
	dw CameruptBitmasks
	dw CentiskorchBitmasks
	dw CharjabugBitmasks
	dw CroagunkBitmasks
	dw DipplinBitmasks
	dw DrifblimBitmasks
	dw DrifloonBitmasks
	dw DrilburBitmasks
	dw DuraludonBitmasks
	dw ElectrikeBitmasks
	dw ExcadrillBitmasks
	dw FlappleBitmasks
	dw FletchinderBitmasks
	dw FletchlingBitmasks
	dw FlygonBitmasks
	dw FroslassBitmasks
	dw GolisopodBitmasks
	dw GrubbinBitmasks
	dw GrumpigBitmasks
	dw HydrappleBitmasks
	dw KingambitBitmasks
	dw LombreBitmasks
	dw LopunnyBitmasks
	dw LotadBitmasks
	dw LudicoloBitmasks
	dw ManectricBitmasks
	dw NumelBitmasks
	dw OverqwilBitmasks
	dw ScraftyBitmasks
	dw ScraggyBitmasks
	dw SealeoBitmasks
	dw ShroomishBitmasks
	dw SizzlipedeBitmasks
	dw SnoruntBitmasks
	dw SnoverBitmasks
	dw SphealBitmasks
	dw SpoinkBitmasks
	dw SwabluBitmasks
	dw TalonflameBitmasks
	dw ToxicroakBitmasks
	dw TrapinchBitmasks
	dw UrsalunabmBitmasks
	dw VibravaBitmasks
	dw VikavoltBitmasks
	dw WalreinBitmasks
	dw WimpodBitmasks
	dw TeddiursabmBitmasks
	dw UrsaringbmBitmasks
	dw AxewBitmasks
	dw FraxureBitmasks
	dw HaxorusBitmasks
	dw CranidosBitmasks
	dw RampardosBitmasks
	dw ShieldonBitmasks
	dw BastiodonBitmasks
	dw PawniardBitmasks
	dw BisharpBitmasks
	dw CetoddleBitmasks
	dw CetitanBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw MimikyuBitmasks
	dw CursolaBitmasks
	dw GalladeBitmasks
	dw MrRimeBitmasks
	dw SirfetchDBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw TyruntBitmasks
	dw TyrantrumBitmasks
	dw AmauraBitmasks
	dw AurorusBitmasks
	dw MunchlaxBitmasks
	dw OrstryxBitmasks
