BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw CharmanderCloneBitmasks
	dw CharmeleonCloneBitmasks
	dw CharizardCloneBitmasks
	dw SquirtleCloneBitmasks
	dw WartortleCloneBitmasks
	dw BlastoiseCloneBitmasks
	dw BulbasaurCloneBitmasks
	dw IvysaurCloneBitmasks
	dw VenusaurCloneBitmasks
	dw HonchkrowBitmasks
	dw AmbipomBitmasks
	dw AnnihilapeBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw DrunsparceBitmasks
	dw ElectivireBitmasks
	dw FarigirafBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw GlaceonBitmasks
	dw LeafeonBitmasks
	dw SylveonBitmasks
	dw GliscorBitmasks
	dw LickilickyBitmasks
	dw MagmortarBitmasks
	dw MagnezoneBitmasks
	dw MamoswineBitmasks
	dw MesmeriaBitmasks
	dw MismagiusBitmasks
	dw PorygonZBitmasks
	dw RhyperiorBitmasks
	dw VenipedeBitmasks
	dw WhirlipedeBitmasks
	dw ScolipedeBitmasks
	dw TangrowthBitmasks
	dw TogekissBitmasks
	dw UrsalunaBitmasks
	dw WeavileBitmasks
	dw WyrdeerBitmasks
	dw YanmegaBitmasks
	dw LileepBitmasks
	dw CradilyBitmasks
	dw AnorithBitmasks
	dw ArmaldoBitmasks
	dw GolettBitmasks
	dw GolurkBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw DeinoBitmasks
	dw ZweilousBitmasks
	dw HydreigonBitmasks
	dw DreepyBitmasks
	dw DrakloakBitmasks
	dw DragapultBitmasks
	dw ImpidimpBitmasks
	dw MorgremBitmasks
	dw GrimmsnarlBitmasks
	dw TinkatinkBitmasks
	dw TinkatuffBitmasks
	dw TinkatonBitmasks
	dw FrigibaxBitmasks
	dw ArctibaxBitmasks
	dw BaxcaliburBitmasks
	dw CharcadetBitmasks
	dw ArmarougeBitmasks
	dw CeruledgeBitmasks
	dw RookideeBitmasks
	dw CorvisquireBitmasks
	dw CorviknightBitmasks
	dw SnoverBitmasks
	dw AbomasnowBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw ApplinBitmasks
	dw DipplinBitmasks
	dw AppletunBitmasks
	dw FlappleBitmasks
	dw HydrappleBitmasks
	dw DuraludonBitmasks
	dw ArchaludonBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw NumelBitmasks
	dw CameruptBitmasks
	dw SizzlipedeBitmasks
	dw CentiskorchBitmasks
	dw GrubbinBitmasks
	dw CharjabugBitmasks
	dw VikavoltBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw ElectrikeBitmasks
	dw ManectricBitmasks
	dw FletchlingBitmasks
	dw FletchinderBitmasks
	dw TalonflameBitmasks
	dw TrapinchBitmasks
	dw VibravaBitmasks
	dw FlygonBitmasks
	dw SnoruntBitmasks
	dw FroslassBitmasks
	dw WimpodBitmasks
	dw GolisopodBitmasks
	dw SpoinkBitmasks
	dw GrumpigBitmasks
	dw PawniardBitmasks
	dw BisharpBitmasks
	dw KingambitBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw OverqwilBitmasks
	dw ScraggyBitmasks
	dw ScraftyBitmasks
	dw SphealBitmasks
	dw SealeoBitmasks
	dw WalreinBitmasks
	dw TeddiursabmBitmasks
	dw UrsaringbmBitmasks
	dw UrsalunabmBitmasks
	dw AxewBitmasks
	dw FraxureBitmasks
	dw HaxorusBitmasks
	dw CranidosBitmasks
	dw RampardosBitmasks
	dw ShieldonBitmasks
	dw BastiodonBitmasks
	dw CetoddleBitmasks
	dw CetitanBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw MimikyuBitmasks
	dw CorsolaGalarianBitmasks
	dw CursolaBitmasks
	dw MrRimeBitmasks
	dw SirfetchDBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw TyruntBitmasks
	dw TyrantrumBitmasks
	dw AmauraBitmasks
	dw AurorusBitmasks
	dw MunchlaxBitmasks
	dw OrstryxBitmasks
	dw RattataAlolanBitmasks
	dw RaticateAlolanBitmasks
	dw RaichuAlolanBitmasks
	dw SandshrewAlolanBitmasks
	dw SandslashAlolanBitmasks
	dw VulpixAlolanBitmasks
	dw NinetalesAlolanBitmasks
	dw DiglettAlolanBitmasks
	dw DugtrioAlolanBitmasks
	dw MeowthAlolanBitmasks
	dw PersianAlolanBitmasks
	dw GeodudeAlolanBitmasks
	dw GravelerAlolanBitmasks
	dw GolemAlolanBitmasks
	dw GrimerAlolanBitmasks
	dw MukAlolanBitmasks
	dw ExeggutorAlolanBitmasks
	dw MarowakAlolanBitmasks
	dw MeowthGalarianBitmasks
	dw PerrserkerBitmasks
	dw PonytaGalarianBitmasks
	dw RapidashGalarianBitmasks
	dw SlowpokeGalarianBitmasks
	dw SlowbroGalarianBitmasks
	dw SlowkingGalarianBitmasks
	dw WeezingGalarianBitmasks
	dw GrowlitheHisuianBitmasks
	dw ArcanineHisuianBitmasks
	dw VoltorbHisuianBitmasks
	dw ElectrodeHisuianBitmasks
	dw TyphlosionHisuianBitmasks
	dw SneaselHisuianBitmasks
	dw SneaslerBitmasks
	dw WooperPaldeanBitmasks
	dw ClodsireBitmasks
	dw TaurosPaldeanFireBitmasks
	dw TaurosPaldeanWaterBitmasks
	dw WatuBitmasks
	dw BounsweetBitmasks
	dw SteeneeBitmasks
	dw TsareenaBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw KleavorBitmasks
	dw GlimmetBitmasks
	dw GlimmoraBitmasks
	dw MareanieBitmasks
	dw ToxapexBitmasks
	dw ZangooseBitmasks
	dw SeviperBitmasks
