FramesPointers:
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba WeedleFrames
	dba KakunaFrames
	dba BeedrillFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba RattataFrames
	dba RaticateFrames
	dba SpearowFrames
	dba FearowFrames
	dba EkansFrames
	dba ArbokFrames
	dba PikachuFrames
	dba RaichuFrames
	dba SandshrewFrames
	dba SandslashFrames
	dba NidoranFFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba ZubatFrames
	dba GolbatFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba DiglettFrames
	dba DugtrioFrames
	dba MeowthFrames
	dba PersianFrames
	dba PsyduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba FarfetchDFrames
	dba DoduoFrames
	dba DodrioFrames
	dba SeelFrames
	dba DewgongFrames
	dba GrimerFrames
	dba MukFrames
	dba ShellderFrames
	dba CloysterFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba LickitungFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba ChanseyFrames
	dba TangelaFrames
	dba KangaskhanFrames
	dba HorseaFrames
	dba SeadraFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba StaryuFrames
	dba StarmieFrames
	dba MrMimeFrames
	dba ScytherFrames
	dba JynxFrames
	dba ElectabuzzFrames
	dba MagmarFrames
	dba PinsirFrames
	dba TaurosFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba LaprasFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba PorygonFrames
	dba OmanyteFrames
	dba OmastarFrames
	dba KabutoFrames
	dba KabutopsFrames
	dba AerodactylFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba SentretFrames
	dba FurretFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba LedybaFrames
	dba LedianFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba CrobatFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba PichuFrames
	dba CleffaFrames
	dba IgglybuffFrames
	dba TogepiFrames
	dba TogeticFrames
	dba NatuFrames
	dba XatuFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba BellossomFrames
	dba MarillFrames
	dba AzumarillFrames
	dba SudowoodoFrames
	dba PolitoedFrames
	dba HoppipFrames
	dba SkiploomFrames
	dba JumpluffFrames
	dba AipomFrames
	dba SunkernFrames
	dba SunfloraFrames
	dba YanmaFrames
	dba WooperFrames
	dba QuagsireFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba MurkrowFrames
	dba SlowkingFrames
	dba MisdreavusFrames
	dba UnownFrames
	dba WobbuffetFrames
	dba GirafarigFrames
	dba PinecoFrames
	dba ForretressFrames
	dba DunsparceFrames
	dba GligarFrames
	dba SteelixFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba QwilfishFrames
	dba ScizorFrames
	dba ShuckleFrames
	dba HeracrossFrames
	dba SneaselFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba CorsolaFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba DelibirdFrames
	dba MantineFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba KingdraFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba Porygon2Frames
	dba StantlerFrames
	dba SmeargleFrames
	dba TyrogueFrames
	dba HitmontopFrames
	dba SmoochumFrames
	dba ElekidFrames
	dba MagbyFrames
	dba MiltankFrames
	dba BlisseyFrames
	dba RaikouFrames
	dba EnteiFrames
	dba SuicuneFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoOhFrames
	dba CelebiFrames
	dba CharmanderCloneFrames
	dba CharmeleonCloneFrames
	dba CharizardCloneFrames
	dba SquirtleCloneFrames
	dba WartortleCloneFrames
	dba BlastoiseCloneFrames
	dba BulbasaurCloneFrames
	dba IvysaurCloneFrames
	dba VenusaurCloneFrames
	dba HonchkrowFrames
	dba AmbipomFrames
	dba AnnihilapeFrames
	dba BagonFrames
	dba ShelgonFrames
	dba SalamenceFrames
	dba DrunsparceFrames
	dba ElectivireFrames
	dba FarigirafFrames
	dba RaltsFrames
	dba KirliaFrames
	dba GardevoirFrames
	dba GalladeFrames
	dba GlaceonFrames
	dba LeafeonFrames
	dba SylveonFrames
	dba GliscorFrames
	dba LickilickyFrames
	dba MagmortarFrames
	dba MagnezoneFrames
	dba MamoswineFrames
	dba MesmeriaFrames
	dba MismagiusFrames
	dba PorygonZFrames
	dba RhyperiorFrames
	dba VenipedeFrames
	dba WhirlipedeFrames
	dba ScolipedeFrames
	dba TangrowthFrames
	dba TogekissFrames
	dba UrsalunaFrames
	dba WeavileFrames
	dba WyrdeerFrames
	dba YanmegaFrames
	dba LileepFrames
	dba CradilyFrames
	dba AnorithFrames
	dba ArmaldoFrames
	dba GolettFrames
	dba GolurkFrames
	dba DuskullFrames
	dba DusclopsFrames
	dba DusknoirFrames
	dba TimburrFrames
	dba GurdurrFrames
	dba ConkeldurrFrames
	dba LarvestaFrames
	dba VolcaronaFrames
	dba DeinoFrames
	dba ZweilousFrames
	dba HydreigonFrames
	dba DreepyFrames
	dba DrakloakFrames
	dba DragapultFrames
	dba ImpidimpFrames
	dba MorgremFrames
	dba GrimmsnarlFrames
	dba TinkatinkFrames
	dba TinkatuffFrames
	dba TinkatonFrames
	dba FrigibaxFrames
	dba ArctibaxFrames
	dba BaxcaliburFrames
	dba CharcadetFrames
	dba ArmarougeFrames
	dba CeruledgeFrames
	dba RookideeFrames
	dba CorvisquireFrames
	dba CorviknightFrames
	dba SnoverFrames
	dba AbomasnowFrames
	dba SwabluFrames
	dba AltariaFrames
	dba ApplinFrames
	dba DipplinFrames
	dba AppletunFrames
	dba FlappleFrames
	dba HydrappleFrames
	dba DuraludonFrames
	dba ArchaludonFrames
	dba ShroomishFrames
	dba BreloomFrames
	dba BunearyFrames
	dba LopunnyFrames
	dba NumelFrames
	dba CameruptFrames
	dba SizzlipedeFrames
	dba CentiskorchFrames
	dba GrubbinFrames
	dba CharjabugFrames
	dba VikavoltFrames
	dba CroagunkFrames
	dba ToxicroakFrames
	dba DrifloonFrames
	dba DrifblimFrames
	dba DrilburFrames
	dba ExcadrillFrames
	dba ElectrikeFrames
	dba ManectricFrames
	dba FletchlingFrames
	dba FletchinderFrames
	dba TalonflameFrames
	dba TrapinchFrames
	dba VibravaFrames
	dba FlygonFrames
	dba SnoruntFrames
	dba FroslassFrames
	dba WimpodFrames
	dba GolisopodFrames
	dba SpoinkFrames
	dba GrumpigFrames
	dba PawniardFrames
	dba BisharpFrames
	dba KingambitFrames
	dba LotadFrames
	dba LombreFrames
	dba LudicoloFrames
	dba OverqwilFrames
	dba ScraggyFrames
	dba ScraftyFrames
	dba SphealFrames
	dba SealeoFrames
	dba WalreinFrames
	dba TeddiursabmFrames
	dba UrsaringbmFrames
	dba UrsalunabmFrames
	dba AxewFrames
	dba FraxureFrames
	dba HaxorusFrames
	dba CranidosFrames
	dba RampardosFrames
	dba ShieldonFrames
	dba BastiodonFrames
	dba CetoddleFrames
	dba CetitanFrames
	dba FeebasFrames
	dba MiloticFrames
	dba MimikyuFrames
	dba CorsolaGalarianFrames
	dba CursolaFrames
	dba MrRimeFrames
	dba SirfetchDFrames
	dba RioluFrames
	dba LucarioFrames
	dba TyruntFrames
	dba TyrantrumFrames
	dba AmauraFrames
	dba AurorusFrames
	dba MunchlaxFrames
	dba OrstryxFrames
	dba RattataAlolanFrames
	dba RaticateAlolanFrames
	dba RaichuAlolanFrames
	dba SandshrewAlolanFrames
	dba SandslashAlolanFrames
	dba VulpixAlolanFrames
	dba NinetalesAlolanFrames
	dba DiglettAlolanFrames
	dba DugtrioAlolanFrames
	dba MeowthAlolanFrames
	dba PersianAlolanFrames
	dba GeodudeAlolanFrames
	dba GravelerAlolanFrames
	dba GolemAlolanFrames
	dba GrimerAlolanFrames
	dba MukAlolanFrames
	dba ExeggutorAlolanFrames
	dba MarowakAlolanFrames
	dba MeowthGalarianFrames
	dba PerrserkerFrames
	dba PonytaGalarianFrames
	dba RapidashGalarianFrames
	dba SlowpokeGalarianFrames
	dba SlowbroGalarianFrames
	dba SlowkingGalarianFrames
	dba WeezingGalarianFrames
	dba GrowlitheHisuianFrames
	dba ArcanineHisuianFrames
	dba VoltorbHisuianFrames
	dba ElectrodeHisuianFrames
	dba TyphlosionHisuianFrames
	dba SneaselHisuianFrames
	dba SneaslerFrames
	dba WooperPaldeanFrames
	dba ClodsireFrames
	dba TaurosPaldeanFireFrames
	dba TaurosPaldeanWaterFrames
	dba WatuFrames
	dba BounsweetFrames
	dba SteeneeFrames
	dba TsareenaFrames
	dba AronFrames
	dba LaironFrames
	dba AggronFrames
	dba KleavorFrames
	dba GlimmetFrames
	dba GlimmoraFrames
	dba MareanieFrames
	dba ToxapexFrames
	dba ZangooseFrames
	dba SeviperFrames
