AnimationIdlePointers:
	dba BulbasaurAnimationIdle
	dba IvysaurAnimationIdle
	dba VenusaurAnimationIdle
	dba CharmanderAnimationIdle
	dba CharmeleonAnimationIdle
	dba CharizardAnimationIdle
	dba SquirtleAnimationIdle
	dba WartortleAnimationIdle
	dba BlastoiseAnimationIdle
	dba CaterpieAnimationIdle
	dba MetapodAnimationIdle
	dba ButterfreeAnimationIdle
	dba WeedleAnimationIdle
	dba KakunaAnimationIdle
	dba BeedrillAnimationIdle
	dba PidgeyAnimationIdle
	dba PidgeottoAnimationIdle
	dba PidgeotAnimationIdle
	dba RattataAnimationIdle
	dba RaticateAnimationIdle
	dba SpearowAnimationIdle
	dba FearowAnimationIdle
	dba EkansAnimationIdle
	dba ArbokAnimationIdle
	dba PikachuAnimationIdle
	dba RaichuAnimationIdle
	dba SandshrewAnimationIdle
	dba SandslashAnimationIdle
	dba NidoranFAnimationIdle
	dba NidorinaAnimationIdle
	dba NidoqueenAnimationIdle
	dba NidoranMAnimationIdle
	dba NidorinoAnimationIdle
	dba NidokingAnimationIdle
	dba ClefairyAnimationIdle
	dba ClefableAnimationIdle
	dba VulpixAnimationIdle
	dba NinetalesAnimationIdle
	dba JigglypuffAnimationIdle
	dba WigglytuffAnimationIdle
	dba ZubatAnimationIdle
	dba GolbatAnimationIdle
	dba OddishAnimationIdle
	dba GloomAnimationIdle
	dba VileplumeAnimationIdle
	dba ParasAnimationIdle
	dba ParasectAnimationIdle
	dba VenonatAnimationIdle
	dba VenomothAnimationIdle
	dba DiglettAnimationIdle
	dba DugtrioAnimationIdle
	dba MeowthAnimationIdle
	dba PersianAnimationIdle
	dba PsyduckAnimationIdle
	dba GolduckAnimationIdle
	dba MankeyAnimationIdle
	dba PrimeapeAnimationIdle
	dba GrowlitheAnimationIdle
	dba ArcanineAnimationIdle
	dba PoliwagAnimationIdle
	dba PoliwhirlAnimationIdle
	dba PoliwrathAnimationIdle
	dba AbraAnimationIdle
	dba KadabraAnimationIdle
	dba AlakazamAnimationIdle
	dba MachopAnimationIdle
	dba MachokeAnimationIdle
	dba MachampAnimationIdle
	dba BellsproutAnimationIdle
	dba WeepinbellAnimationIdle
	dba VictreebelAnimationIdle
	dba TentacoolAnimationIdle
	dba TentacruelAnimationIdle
	dba GeodudeAnimationIdle
	dba GravelerAnimationIdle
	dba GolemAnimationIdle
	dba PonytaAnimationIdle
	dba RapidashAnimationIdle
	dba SlowpokeAnimationIdle
	dba SlowbroAnimationIdle
	dba MagnemiteAnimationIdle
	dba MagnetonAnimationIdle
	dba FarfetchDAnimationIdle
	dba DoduoAnimationIdle
	dba DodrioAnimationIdle
	dba SeelAnimationIdle
	dba DewgongAnimationIdle
	dba GrimerAnimationIdle
	dba MukAnimationIdle
	dba ShellderAnimationIdle
	dba CloysterAnimationIdle
	dba GastlyAnimationIdle
	dba HaunterAnimationIdle
	dba GengarAnimationIdle
	dba OnixAnimationIdle
	dba DrowzeeAnimationIdle
	dba HypnoAnimationIdle
	dba KrabbyAnimationIdle
	dba KinglerAnimationIdle
	dba VoltorbAnimationIdle
	dba ElectrodeAnimationIdle
	dba ExeggcuteAnimationIdle
	dba ExeggutorAnimationIdle
	dba CuboneAnimationIdle
	dba MarowakAnimationIdle
	dba HitmonleeAnimationIdle
	dba HitmonchanAnimationIdle
	dba LickitungAnimationIdle
	dba KoffingAnimationIdle
	dba WeezingAnimationIdle
	dba RhyhornAnimationIdle
	dba RhydonAnimationIdle
	dba ChanseyAnimationIdle
	dba TangelaAnimationIdle
	dba KangaskhanAnimationIdle
	dba HorseaAnimationIdle
	dba SeadraAnimationIdle
	dba GoldeenAnimationIdle
	dba SeakingAnimationIdle
	dba StaryuAnimationIdle
	dba StarmieAnimationIdle
	dba MrMimeAnimationIdle
	dba ScytherAnimationIdle
	dba JynxAnimationIdle
	dba ElectabuzzAnimationIdle
	dba MagmarAnimationIdle
	dba PinsirAnimationIdle
	dba TaurosAnimationIdle
	dba MagikarpAnimationIdle
	dba GyaradosAnimationIdle
	dba LaprasAnimationIdle
	dba DittoAnimationIdle
	dba EeveeAnimationIdle
	dba VaporeonAnimationIdle
	dba JolteonAnimationIdle
	dba FlareonAnimationIdle
	dba PorygonAnimationIdle
	dba OmanyteAnimationIdle
	dba OmastarAnimationIdle
	dba KabutoAnimationIdle
	dba KabutopsAnimationIdle
	dba AerodactylAnimationIdle
	dba SnorlaxAnimationIdle
	dba ArticunoAnimationIdle
	dba ZapdosAnimationIdle
	dba MoltresAnimationIdle
	dba DratiniAnimationIdle
	dba DragonairAnimationIdle
	dba DragoniteAnimationIdle
	dba MewtwoAnimationIdle
	dba MewAnimationIdle
	dba ChikoritaAnimationIdle
	dba BayleefAnimationIdle
	dba MeganiumAnimationIdle
	dba CyndaquilAnimationIdle
	dba QuilavaAnimationIdle
	dba TyphlosionAnimationIdle
	dba TotodileAnimationIdle
	dba CroconawAnimationIdle
	dba FeraligatrAnimationIdle
	dba SentretAnimationIdle
	dba FurretAnimationIdle
	dba HoothootAnimationIdle
	dba NoctowlAnimationIdle
	dba LedybaAnimationIdle
	dba LedianAnimationIdle
	dba SpinarakAnimationIdle
	dba AriadosAnimationIdle
	dba CrobatAnimationIdle
	dba ChinchouAnimationIdle
	dba LanturnAnimationIdle
	dba PichuAnimationIdle
	dba CleffaAnimationIdle
	dba IgglybuffAnimationIdle
	dba TogepiAnimationIdle
	dba TogeticAnimationIdle
	dba NatuAnimationIdle
	dba XatuAnimationIdle
	dba MareepAnimationIdle
	dba FlaaffyAnimationIdle
	dba AmpharosAnimationIdle
	dba BellossomAnimationIdle
	dba MarillAnimationIdle
	dba AzumarillAnimationIdle
	dba SudowoodoAnimationIdle
	dba PolitoedAnimationIdle
	dba HoppipAnimationIdle
	dba SkiploomAnimationIdle
	dba JumpluffAnimationIdle
	dba AipomAnimationIdle
	dba SunkernAnimationIdle
	dba SunfloraAnimationIdle
	dba YanmaAnimationIdle
	dba WooperAnimationIdle
	dba QuagsireAnimationIdle
	dba EspeonAnimationIdle
	dba UmbreonAnimationIdle
	dba MurkrowAnimationIdle
	dba SlowkingAnimationIdle
	dba MisdreavusAnimationIdle
	dba UnownAnimationIdle
	dba WobbuffetAnimationIdle
	dba GirafarigAnimationIdle
	dba PinecoAnimationIdle
	dba ForretressAnimationIdle
	dba DunsparceAnimationIdle
	dba GligarAnimationIdle
	dba SteelixAnimationIdle
	dba SnubbullAnimationIdle
	dba GranbullAnimationIdle
	dba QwilfishAnimationIdle
	dba ScizorAnimationIdle
	dba ShuckleAnimationIdle
	dba HeracrossAnimationIdle
	dba SneaselAnimationIdle
	dba TeddiursaAnimationIdle
	dba UrsaringAnimationIdle
	dba SlugmaAnimationIdle
	dba MagcargoAnimationIdle
	dba SwinubAnimationIdle
	dba PiloswineAnimationIdle
	dba CorsolaAnimationIdle
	dba RemoraidAnimationIdle
	dba OctilleryAnimationIdle
	dba DelibirdAnimationIdle
	dba MantineAnimationIdle
	dba SkarmoryAnimationIdle
	dba HoundourAnimationIdle
	dba HoundoomAnimationIdle
	dba KingdraAnimationIdle
	dba PhanpyAnimationIdle
	dba DonphanAnimationIdle
	dba Porygon2AnimationIdle
	dba StantlerAnimationIdle
	dba SmeargleAnimationIdle
	dba TyrogueAnimationIdle
	dba HitmontopAnimationIdle
	dba SmoochumAnimationIdle
	dba ElekidAnimationIdle
	dba MagbyAnimationIdle
	dba MiltankAnimationIdle
	dba BlisseyAnimationIdle
	dba RaikouAnimationIdle
	dba EnteiAnimationIdle
	dba SuicuneAnimationIdle
	dba LarvitarAnimationIdle
	dba PupitarAnimationIdle
	dba TyranitarAnimationIdle
	dba LugiaAnimationIdle
	dba HoOhAnimationIdle
	dba CelebiAnimationIdle
	dba CharmanderCloneAnimationIdle
	dba CharmeleonCloneAnimationIdle
	dba CharizardCloneAnimationIdle
	dba SquirtleCloneAnimationIdle
	dba WartortleCloneAnimationIdle
	dba BlastoiseCloneAnimationIdle
	dba BulbasaurCloneAnimationIdle
	dba IvysaurCloneAnimationIdle
	dba VenusaurCloneAnimationIdle
	dba HonchkrowAnimationIdle
	dba AmbipomAnimationIdle
	dba AnnihilapeAnimationIdle
	dba BagonAnimationIdle
	dba ShelgonAnimationIdle
	dba SalamenceAnimationIdle
	dba DrunsparceAnimationIdle
	dba ElectivireAnimationIdle
	dba FarigirafAnimationIdle
	dba RaltsAnimationIdle
	dba KirliaAnimationIdle
	dba GardevoirAnimationIdle
	dba GalladeAnimationIdle
	dba GlaceonAnimationIdle
	dba LeafeonAnimationIdle
	dba SylveonAnimationIdle
	dba GliscorAnimationIdle
	dba LickilickyAnimationIdle
	dba MagmortarAnimationIdle
	dba MagnezoneAnimationIdle
	dba MamoswineAnimationIdle
	dba MesmeriaAnimationIdle
	dba MismagiusAnimationIdle
	dba PorygonZAnimationIdle
	dba RhyperiorAnimationIdle
	dba VenipedeAnimationIdle
	dba WhirlipedeAnimationIdle
	dba ScolipedeAnimationIdle
	dba TangrowthAnimationIdle
	dba TogekissAnimationIdle
	dba UrsalunaAnimationIdle
	dba WeavileAnimationIdle
	dba WyrdeerAnimationIdle
	dba YanmegaAnimationIdle
	dba LileepAnimationIdle
	dba CradilyAnimationIdle
	dba AnorithAnimationIdle
	dba ArmaldoAnimationIdle
	dba GolettAnimationIdle
	dba GolurkAnimationIdle
	dba DuskullAnimationIdle
	dba DusclopsAnimationIdle
	dba DusknoirAnimationIdle
	dba TimburrAnimationIdle
	dba GurdurrAnimationIdle
	dba ConkeldurrAnimationIdle
	dba LarvestaAnimationIdle
	dba VolcaronaAnimationIdle
	dba DeinoAnimationIdle
	dba ZweilousAnimationIdle
	dba HydreigonAnimationIdle
	dba DreepyAnimationIdle
	dba DrakloakAnimationIdle
	dba DragapultAnimationIdle
	dba ImpidimpAnimationIdle
	dba MorgremAnimationIdle
	dba GrimmsnarlAnimationIdle
	dba TinkatinkAnimationIdle
	dba TinkatuffAnimationIdle
	dba TinkatonAnimationIdle
	dba FrigibaxAnimationIdle
	dba ArctibaxAnimationIdle
	dba BaxcaliburAnimationIdle
	dba CharcadetAnimationIdle
	dba ArmarougeAnimationIdle
	dba CeruledgeAnimationIdle
	dba RookideeAnimationIdle
	dba CorvisquireAnimationIdle
	dba CorviknightAnimationIdle
	dba SnoverAnimationIdle
	dba AbomasnowAnimationIdle
	dba SwabluAnimationIdle
	dba AltariaAnimationIdle
	dba ApplinAnimationIdle
	dba DipplinAnimationIdle
	dba AppletunAnimationIdle
	dba FlappleAnimationIdle
	dba HydrappleAnimationIdle
	dba DuraludonAnimationIdle
	dba ArchaludonAnimationIdle
	dba ShroomishAnimationIdle
	dba BreloomAnimationIdle
	dba BunearyAnimationIdle
	dba LopunnyAnimationIdle
	dba NumelAnimationIdle
	dba CameruptAnimationIdle
	dba SizzlipedeAnimationIdle
	dba CentiskorchAnimationIdle
	dba GrubbinAnimationIdle
	dba CharjabugAnimationIdle
	dba VikavoltAnimationIdle
	dba CroagunkAnimationIdle
	dba ToxicroakAnimationIdle
	dba DrifloonAnimationIdle
	dba DrifblimAnimationIdle
	dba DrilburAnimationIdle
	dba ExcadrillAnimationIdle
	dba KotoraAnimationIdle
	dba RaitoraAnimationIdle
	dba GorotoraAnimationIdle
	dba FletchlingAnimationIdle
	dba FletchinderAnimationIdle
	dba TalonflameAnimationIdle
	dba TrapinchAnimationIdle
	dba VibravaAnimationIdle
	dba FlygonAnimationIdle
	dba SnoruntAnimationIdle
	dba FroslassAnimationIdle
	dba WimpodAnimationIdle
	dba GolisopodAnimationIdle
	dba SpoinkAnimationIdle
	dba GrumpigAnimationIdle
	dba PawniardAnimationIdle
	dba BisharpAnimationIdle
	dba KingambitAnimationIdle
	dba LotadAnimationIdle
	dba LombreAnimationIdle
	dba LudicoloAnimationIdle
	dba OverqwilAnimationIdle
	dba ScraggyAnimationIdle
	dba ScraftyAnimationIdle
	dba SphealAnimationIdle
	dba SealeoAnimationIdle
	dba WalreinAnimationIdle
	dba TeddiursabmAnimationIdle
	dba UrsaringbmAnimationIdle
	dba UrsalunabmAnimationIdle
	dba AxewAnimationIdle
	dba FraxureAnimationIdle
	dba HaxorusAnimationIdle
	dba CranidosAnimationIdle
	dba RampardosAnimationIdle
	dba ShieldonAnimationIdle
	dba BastiodonAnimationIdle
	dba CetoddleAnimationIdle
	dba CetitanAnimationIdle
	dba FeebasAnimationIdle
	dba MiloticAnimationIdle
	dba MimikyuAnimationIdle
	dba CorsolaGalarianAnimationIdle
	dba CursolaAnimationIdle
	dba MrRimeAnimationIdle
	dba SirfetchDAnimationIdle
	dba RioluAnimationIdle
	dba LucarioAnimationIdle
	dba TyruntAnimationIdle
	dba TyrantrumAnimationIdle
	dba AmauraAnimationIdle
	dba AurorusAnimationIdle
	dba MunchlaxAnimationIdle
	dba TorkoalAnimationIdle
	dba RattataAlolanAnimationIdle
	dba RaticateAlolanAnimationIdle
	dba RaichuAlolanAnimationIdle
	dba SandshrewAlolanAnimationIdle
	dba SandslashAlolanAnimationIdle
	dba VulpixAlolanAnimationIdle
	dba NinetalesAlolanAnimationIdle
	dba DiglettAlolanAnimationIdle
	dba DugtrioAlolanAnimationIdle
	dba MeowthAlolanAnimationIdle
	dba PersianAlolanAnimationIdle
	dba GeodudeAlolanAnimationIdle
	dba GravelerAlolanAnimationIdle
	dba GolemAlolanAnimationIdle
	dba GrimerAlolanAnimationIdle
	dba MukAlolanAnimationIdle
	dba ExeggutorAlolanAnimationIdle
	dba MarowakAlolanAnimationIdle
	dba MeowthGalarianAnimationIdle
	dba PerrserkerAnimationIdle
	dba PonytaGalarianAnimationIdle
	dba RapidashGalarianAnimationIdle
	dba SlowpokeGalarianAnimationIdle
	dba SlowbroGalarianAnimationIdle
	dba SlowkingGalarianAnimationIdle
	dba WeezingGalarianAnimationIdle
	dba GrowlitheHisuianAnimationIdle
	dba ArcanineHisuianAnimationIdle
	dba VoltorbHisuianAnimationIdle
	dba ElectrodeHisuianAnimationIdle
	dba TyphlosionHisuianAnimationIdle
	dba SneaselHisuianAnimationIdle
	dba SneaslerAnimationIdle
	dba WooperPaldeanAnimationIdle
	dba ClodsireAnimationIdle
	dba TaurosPaldeanFireAnimationIdle
	dba TaurosPaldeanWaterAnimationIdle
	dba WatuAnimationIdle
	dba BounsweetAnimationIdle
	dba SteeneeAnimationIdle
	dba TsareenaAnimationIdle
	dba AronAnimationIdle
	dba LaironAnimationIdle
	dba AggronAnimationIdle
	dba KleavorAnimationIdle
	dba GlimmetAnimationIdle
	dba GlimmoraAnimationIdle
	dba MareanieAnimationIdle
	dba ToxapexAnimationIdle
	dba ZangooseAnimationIdle
	dba SeviperAnimationIdle
	dba ShuppetAnimationIdle
	dba BanetteAnimationIdle
	dba ArchenAnimationIdle
	dba ArcheopsAnimationIdle
	dba TirtougaAnimationIdle
	dba CarracostaAnimationIdle
	dba LitwickAnimationIdle
	dba LampentAnimationIdle
	dba ChandelureAnimationIdle
	dba JoltikAnimationIdle
	dba GalvantulaAnimationIdle
	dba MawileAnimationIdle
	dba NoibatAnimationIdle
	dba NoivernAnimationIdle
	dba SalanditAnimationIdle
	dba SalazzleAnimationIdle
	dba FlittleAnimationIdle
	dba EspathraAnimationIdle
	dba FinizenAnimationIdle
	dba PalafinAnimationIdle
	dba AzurillAnimationIdle
	dba WynautAnimationIdle
	dba BonslyAnimationIdle
	dba MimeJrAnimationIdle
	dba HappinyAnimationIdle
	dba MantykeAnimationIdle
