AnimationIdlePointers:
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmontopAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw HonchkrowAnimationIdle
	dw AmbipomAnimationIdle
	dw AnnihilapeAnimationIdle
	dw BagonAnimationIdle
	dw DrunsparceAnimationIdle
	dw ElectivireAnimationIdle
	dw FarigirafAnimationIdle
	dw GardevoirAnimationIdle
	dw GlaceonAnimationIdle
	dw GliscorAnimationIdle
	dw KirliaAnimationIdle
	dw LeafeonAnimationIdle
	dw LickilickyAnimationIdle
	dw MagmortarAnimationIdle
	dw MagnezoneAnimationIdle
	dw MamoswineAnimationIdle
	dw MesmeriaAnimationIdle
	dw MismagiusAnimationIdle
	dw PorygonZAnimationIdle
	dw RaltsAnimationIdle
	dw RhyperiorAnimationIdle
	dw SalamenceAnimationIdle
	dw ScolipedeAnimationIdle
	dw ShelgonAnimationIdle
	dw TangrowthAnimationIdle
	dw TogekissAnimationIdle
	dw UrsalunaAnimationIdle
	dw VenipedeAnimationIdle
	dw WeavileAnimationIdle
	dw WhirlipedeAnimationIdle
	dw WyrdeerAnimationIdle
	dw YanmegaAnimationIdle
	dw LileepAnimationIdle
	dw CradilyAnimationIdle
	dw ArmaldoAnimationIdle
	dw GolettAnimationIdle
	dw GolurkAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw DusknoirAnimationIdle
	dw TimburrAnimationIdle
	dw GurdurrAnimationIdle
	dw ConkeldurrAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcaronaAnimationIdle
	dw DeinoAnimationIdle
	dw ZweilousAnimationIdle
	dw HydreigonAnimationIdle
	dw DreepyAnimationIdle
	dw DrakloakAnimationIdle
	dw DragapultAnimationIdle
	dw ImpidimpAnimationIdle
	dw MorgremAnimationIdle
	dw GrimmsnarlAnimationIdle
	dw TinkatinkAnimationIdle
	dw TinkatuffAnimationIdle
	dw TinkatonAnimationIdle
	dw FrigibaxAnimationIdle
	dw ArctibaxAnimationIdle
	dw BaxcaliburAnimationIdle
	dw CharcadetAnimationIdle
	dw ArmarougeAnimationIdle
	dw CeruledgeAnimationIdle
	dw SylveonAnimationIdle
	dw RookideeAnimationIdle
	dw CorvisquireAnimationIdle
	dw CorviknightAnimationIdle
	dw AbomasnowAnimationIdle
	dw AltariaAnimationIdle
	dw AnorithAnimationIdle
	dw AppletunAnimationIdle
	dw ApplinAnimationIdle
	dw ArchaludonAnimationIdle
	dw BreloomAnimationIdle
	dw BunearyAnimationIdle
	dw CameruptAnimationIdle
	dw CentiskorchAnimationIdle
	dw CharjabugAnimationIdle
	dw CroagunkAnimationIdle
	dw DipplinAnimationIdle
	dw DrifblimAnimationIdle
	dw DrifloonAnimationIdle
	dw DrilburAnimationIdle
	dw DuraludonAnimationIdle
	dw ElectrikeAnimationIdle
	dw ExcadrillAnimationIdle
	dw FlappleAnimationIdle
	dw FletchinderAnimationIdle
	dw FletchlingAnimationIdle
	dw FlygonAnimationIdle
	dw FroslassAnimationIdle
	dw GolisopodAnimationIdle
	dw GrubbinAnimationIdle
	dw GrumpigAnimationIdle
	dw HydrappleAnimationIdle
	dw KingambitAnimationIdle
	dw LombreAnimationIdle
	dw LopunnyAnimationIdle
	dw LotadAnimationIdle
	dw LudicoloAnimationIdle
	dw ManectricAnimationIdle
	dw NumelAnimationIdle
	dw OverqwilAnimationIdle
	dw ScraftyAnimationIdle
	dw ScraggyAnimationIdle
	dw SealeoAnimationIdle
	dw ShroomishAnimationIdle
	dw SizzlipedeAnimationIdle
	dw SnoruntAnimationIdle
	dw SnoverAnimationIdle
	dw SphealAnimationIdle
	dw SpoinkAnimationIdle
	dw SwabluAnimationIdle
	dw TalonflameAnimationIdle
	dw ToxicroakAnimationIdle
	dw TrapinchAnimationIdle
	dw UrsalunabmAnimationIdle
	dw VibravaAnimationIdle
	dw VikavoltAnimationIdle
	dw WalreinAnimationIdle
	dw WimpodAnimationIdle
	dw TeddiursabmAnimationIdle
	dw UrsaringbmAnimationIdle
	dw AxewAnimationIdle
	dw FraxureAnimationIdle
	dw HaxorusAnimationIdle
	dw CranidosAnimationIdle
	dw RampardosAnimationIdle
	dw ShieldonAnimationIdle
	dw BastiodonAnimationIdle
	dw PawniardAnimationIdle
	dw BisharpAnimationIdle
	dw CetoddleAnimationIdle
	dw CetitanAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw MimikyuAnimationIdle
	dw CursolaAnimationIdle
	dw GalladeAnimationIdle
	dw MrRimeAnimationIdle
	dw SirfetchDAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw TyruntAnimationIdle
	dw TyrantrumAnimationIdle
	dw AmauraAnimationIdle
	dw AurorusAnimationIdle
	dw MunchlaxAnimationIdle
	dw OrstryxAnimationIdle
	dw RattataAlolanAnimationIdle
	dw RaticateAlolanAnimationIdle
	dw RaichuAlolanAnimationIdle
	dw SandshrewAlolanAnimationIdle
	dw SandslashAlolanAnimationIdle
	dw VulpixAlolanAnimationIdle
	dw NinetalesAlolanAnimationIdle
	dw DiglettAlolanAnimationIdle
	dw DugtrioAlolanAnimationIdle
	dw MeowthAlolanAnimationIdle
	dw PersianAlolanAnimationIdle
	dw GeodudeAlolanAnimationIdle
	dw GravelerAlolanAnimationIdle
	dw GolemAlolanAnimationIdle
	dw GrimerAlolanAnimationIdle
	dw MukAlolanAnimationIdle
	dw ExeggutorAlolanAnimationIdle
	dw MarowakAlolanAnimationIdle
	dw MeowthGalarianAnimationIdle
	dw PerrserkerAnimationIdle
	dw PonytaGalarianAnimationIdle
	dw RapidashGalarianAnimationIdle
	dw SlowpokeGalarianAnimationIdle
	dw SlowbroGalarianAnimationIdle
	dw WeezingGalarianAnimationIdle
	dw SlowkingGalarianAnimationIdle
	dw CorsolaGalarianAnimationIdle
	dw GrowlitheHisuianAnimationIdle
	dw ArcanineHisuianAnimationIdle
	dw VoltorbHisuianAnimationIdle
	dw ElectrodeHisuianAnimationIdle
	dw TyphlosionHisuianAnimationIdle
	dw SneaselHisuianAnimationIdle
	dw WooperPaldeanAnimationIdle
	dw ClodsireAnimationIdle
	dw TaurosPaldeanFireAnimationIdle
	dw TaurosPaldeanWaterAnimationIdle
	dw SneaslerAnimationIdle
	dw WatuAnimationIdle
	dw BounsweetAnimationIdle
	dw SteeneeAnimationIdle
	dw TsareenaAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw KleavorAnimationIdle
	dw GlimmetAnimationIdle
	dw MareanieAnimationIdle
	dw ToxapexAnimationIdle
	dw ZangooseAnimationIdle
	dw SeviperAnimationIdle
	dw GlimmoraAnimationIdle
