UnownAnimationPointers:
	dba UnownAAnimation
	dba UnownBAnimation
	dba UnownCAnimation
	dba UnownDAnimation
	dba UnownEAnimation
	dba UnownFAnimation
	dba UnownGAnimation
	dba UnownHAnimation
	dba UnownIAnimation
	dba UnownJAnimation
	dba UnownKAnimation
	dba UnownLAnimation
	dba UnownMAnimation
	dba UnownNAnimation
	dba UnownOAnimation
	dba UnownPAnimation
	dba UnownQAnimation
	dba UnownRAnimation
	dba UnownSAnimation
	dba UnownTAnimation
	dba UnownUAnimation
	dba UnownVAnimation
	dba UnownWAnimation
	dba UnownXAnimation
	dba UnownYAnimation
	dba UnownZAnimation
