UnownAnimationIdlePointers:
	dba UnownAAnimationIdle
	dba UnownBAnimationIdle
	dba UnownCAnimationIdle
	dba UnownDAnimationIdle
	dba UnownEAnimationIdle
	dba UnownFAnimationIdle
	dba UnownGAnimationIdle
	dba UnownHAnimationIdle
	dba UnownIAnimationIdle
	dba UnownJAnimationIdle
	dba UnownKAnimationIdle
	dba UnownLAnimationIdle
	dba UnownMAnimationIdle
	dba UnownNAnimationIdle
	dba UnownOAnimationIdle
	dba UnownPAnimationIdle
	dba UnownQAnimationIdle
	dba UnownRAnimationIdle
	dba UnownSAnimationIdle
	dba UnownTAnimationIdle
	dba UnownUAnimationIdle
	dba UnownVAnimationIdle
	dba UnownWAnimationIdle
	dba UnownXAnimationIdle
	dba UnownYAnimationIdle
	dba UnownZAnimationIdle
