; Per-species MENU icons (party menu, PC, naming screen, trade, fly, etc).
; Each icon is 8 tiles (two 16x16 frames side by side in a 32x16 png).
; The overworld walking sprites use gfx/icons.asm instead.
; Species without their own art fall back to the old class icons;
; to give one its own icon, add gfx/menu_icons/<species>.png and update the
; INCBIN filename on its line below.

SECTION "Menu Icon Pointers", ROMX

INCLUDE "data/menu_icon_pointers.asm"

SECTION "Menu Icons 1", ROMX

BulbasaurMenuIcon:   INCBIN "gfx/menu_icons/bulbasaur.2bpp"
IvysaurMenuIcon:     INCBIN "gfx/menu_icons/ivysaur.2bpp"
VenusaurMenuIcon:    INCBIN "gfx/menu_icons/venusaur.2bpp"
CharmanderMenuIcon:  INCBIN "gfx/menu_icons/charmander.2bpp"
CharmeleonMenuIcon:  INCBIN "gfx/menu_icons/charmeleon.2bpp"
CharizardMenuIcon:   INCBIN "gfx/menu_icons/charizard.2bpp"
SquirtleMenuIcon:    INCBIN "gfx/menu_icons/squirtle.2bpp"
WartortleMenuIcon:   INCBIN "gfx/menu_icons/wartortle.2bpp"
BlastoiseMenuIcon:   INCBIN "gfx/menu_icons/blastoise.2bpp"
CaterpieMenuIcon:    INCBIN "gfx/menu_icons/caterpie.2bpp"
MetapodMenuIcon:     INCBIN "gfx/menu_icons/metapod.2bpp"
ButterfreeMenuIcon:  INCBIN "gfx/menu_icons/butterfree.2bpp"
WeedleMenuIcon:      INCBIN "gfx/menu_icons/weedle.2bpp"
KakunaMenuIcon:      INCBIN "gfx/menu_icons/kakuna.2bpp"
BeedrillMenuIcon:    INCBIN "gfx/menu_icons/beedrill.2bpp"
PidgeyMenuIcon:      INCBIN "gfx/menu_icons/pidgey.2bpp"
PidgeottoMenuIcon:   INCBIN "gfx/menu_icons/pidgeotto.2bpp"
PidgeotMenuIcon:     INCBIN "gfx/menu_icons/pidgeot.2bpp"
RattataMenuIcon:     INCBIN "gfx/menu_icons/rattata.2bpp"
RaticateMenuIcon:    INCBIN "gfx/menu_icons/raticate.2bpp"
SpearowMenuIcon:     INCBIN "gfx/menu_icons/spearow.2bpp"
FearowMenuIcon:      INCBIN "gfx/menu_icons/fearow.2bpp"
EkansMenuIcon:       INCBIN "gfx/menu_icons/ekans.2bpp"
ArbokMenuIcon:       INCBIN "gfx/menu_icons/arbok.2bpp"
PikachuMenuIcon:     INCBIN "gfx/menu_icons/pikachu.2bpp"
RaichuMenuIcon:      INCBIN "gfx/menu_icons/raichu.2bpp"
SandshrewMenuIcon:   INCBIN "gfx/menu_icons/sandshrew.2bpp"
SandslashMenuIcon:   INCBIN "gfx/menu_icons/sandslash.2bpp"
NidoranFMenuIcon:    INCBIN "gfx/menu_icons/nidoran_f.2bpp"
NidorinaMenuIcon:    INCBIN "gfx/menu_icons/nidorina.2bpp"
NidoqueenMenuIcon:   INCBIN "gfx/menu_icons/nidoqueen.2bpp"
NidoranMMenuIcon:    INCBIN "gfx/menu_icons/nidoran_m.2bpp"
NidorinoMenuIcon:    INCBIN "gfx/menu_icons/nidorino.2bpp"
NidokingMenuIcon:    INCBIN "gfx/menu_icons/nidoking.2bpp"
ClefairyMenuIcon:    INCBIN "gfx/menu_icons/clefairy.2bpp"
ClefableMenuIcon:    INCBIN "gfx/menu_icons/clefable.2bpp"
VulpixMenuIcon:      INCBIN "gfx/menu_icons/vulpix.2bpp"
NinetalesMenuIcon:   INCBIN "gfx/menu_icons/ninetales.2bpp"
JigglypuffMenuIcon:  INCBIN "gfx/menu_icons/jigglypuff.2bpp"
WigglytuffMenuIcon:  INCBIN "gfx/menu_icons/wigglytuff.2bpp"
ZubatMenuIcon:       INCBIN "gfx/menu_icons/zubat.2bpp"
GolbatMenuIcon:      INCBIN "gfx/menu_icons/golbat.2bpp"
OddishMenuIcon:      INCBIN "gfx/menu_icons/oddish.2bpp"
GloomMenuIcon:       INCBIN "gfx/menu_icons/gloom.2bpp"
VileplumeMenuIcon:   INCBIN "gfx/menu_icons/vileplume.2bpp"
ParasMenuIcon:       INCBIN "gfx/menu_icons/paras.2bpp"
ParasectMenuIcon:    INCBIN "gfx/menu_icons/parasect.2bpp"
VenonatMenuIcon:     INCBIN "gfx/menu_icons/venonat.2bpp"
VenomothMenuIcon:    INCBIN "gfx/menu_icons/venomoth.2bpp"
DiglettMenuIcon:     INCBIN "gfx/menu_icons/diglett.2bpp"
DugtrioMenuIcon:     INCBIN "gfx/menu_icons/dugtrio.2bpp"
MeowthMenuIcon:      INCBIN "gfx/menu_icons/meowth.2bpp"
PersianMenuIcon:     INCBIN "gfx/menu_icons/persian.2bpp"
PsyduckMenuIcon:     INCBIN "gfx/menu_icons/psyduck.2bpp"
GolduckMenuIcon:     INCBIN "gfx/menu_icons/golduck.2bpp"
MankeyMenuIcon:      INCBIN "gfx/menu_icons/mankey.2bpp"
PrimeapeMenuIcon:    INCBIN "gfx/menu_icons/primeape.2bpp"
GrowlitheMenuIcon:   INCBIN "gfx/menu_icons/growlithe.2bpp"
ArcanineMenuIcon:    INCBIN "gfx/menu_icons/arcanine.2bpp"
PoliwagMenuIcon:     INCBIN "gfx/menu_icons/poliwag.2bpp"

SECTION "Menu Icons 2", ROMX

PoliwhirlMenuIcon:   INCBIN "gfx/menu_icons/poliwhirl.2bpp"
PoliwrathMenuIcon:   INCBIN "gfx/menu_icons/poliwrath.2bpp"
AbraMenuIcon:        INCBIN "gfx/menu_icons/abra.2bpp"
KadabraMenuIcon:     INCBIN "gfx/menu_icons/kadabra.2bpp"
AlakazamMenuIcon:    INCBIN "gfx/menu_icons/alakazam.2bpp"
MachopMenuIcon:      INCBIN "gfx/menu_icons/machop.2bpp"
MachokeMenuIcon:     INCBIN "gfx/menu_icons/machoke.2bpp"
MachampMenuIcon:     INCBIN "gfx/menu_icons/machamp.2bpp"
BellsproutMenuIcon:  INCBIN "gfx/menu_icons/bellsprout.2bpp"
WeepinbellMenuIcon:  INCBIN "gfx/menu_icons/weepinbell.2bpp"
VictreebelMenuIcon:  INCBIN "gfx/menu_icons/victreebel.2bpp"
TentacoolMenuIcon:   INCBIN "gfx/menu_icons/tentacool.2bpp"
TentacruelMenuIcon:  INCBIN "gfx/menu_icons/tentacruel.2bpp"
GeodudeMenuIcon:     INCBIN "gfx/menu_icons/geodude.2bpp"
GravelerMenuIcon:    INCBIN "gfx/menu_icons/graveler.2bpp"
GolemMenuIcon:       INCBIN "gfx/menu_icons/golem.2bpp"
PonytaMenuIcon:      INCBIN "gfx/menu_icons/ponyta.2bpp"
RapidashMenuIcon:    INCBIN "gfx/menu_icons/rapidash.2bpp"
SlowpokeMenuIcon:    INCBIN "gfx/menu_icons/slowpoke.2bpp"
SlowbroMenuIcon:     INCBIN "gfx/menu_icons/slowbro.2bpp"
MagnemiteMenuIcon:   INCBIN "gfx/menu_icons/magnemite.2bpp"
MagnetonMenuIcon:    INCBIN "gfx/menu_icons/magneton.2bpp"
FarfetchDMenuIcon:   INCBIN "gfx/menu_icons/farfetch_d.2bpp"
DoduoMenuIcon:       INCBIN "gfx/menu_icons/doduo.2bpp"
DodrioMenuIcon:      INCBIN "gfx/menu_icons/dodrio.2bpp"
SeelMenuIcon:        INCBIN "gfx/menu_icons/seel.2bpp"
DewgongMenuIcon:     INCBIN "gfx/menu_icons/dewgong.2bpp"
GrimerMenuIcon:      INCBIN "gfx/menu_icons/grimer.2bpp"
MukMenuIcon:         INCBIN "gfx/menu_icons/muk.2bpp"
ShellderMenuIcon:    INCBIN "gfx/menu_icons/shellder.2bpp"
CloysterMenuIcon:    INCBIN "gfx/menu_icons/cloyster.2bpp"
GastlyMenuIcon:      INCBIN "gfx/menu_icons/gastly.2bpp"
HaunterMenuIcon:     INCBIN "gfx/menu_icons/haunter.2bpp"
GengarMenuIcon:      INCBIN "gfx/menu_icons/gengar.2bpp"
OnixMenuIcon:        INCBIN "gfx/menu_icons/onix.2bpp"
DrowzeeMenuIcon:     INCBIN "gfx/menu_icons/drowzee.2bpp"
HypnoMenuIcon:       INCBIN "gfx/menu_icons/hypno.2bpp"
KrabbyMenuIcon:      INCBIN "gfx/menu_icons/krabby.2bpp"
KinglerMenuIcon:     INCBIN "gfx/menu_icons/kingler.2bpp"
VoltorbMenuIcon:     INCBIN "gfx/menu_icons/voltorb.2bpp"
ElectrodeMenuIcon:   INCBIN "gfx/menu_icons/electrode.2bpp"
ExeggcuteMenuIcon:   INCBIN "gfx/menu_icons/exeggcute.2bpp"
ExeggutorMenuIcon:   INCBIN "gfx/menu_icons/exeggutor.2bpp"
CuboneMenuIcon:      INCBIN "gfx/menu_icons/cubone.2bpp"
MarowakMenuIcon:     INCBIN "gfx/menu_icons/marowak.2bpp"
HitmonleeMenuIcon:   INCBIN "gfx/menu_icons/hitmonlee.2bpp"
HitmonchanMenuIcon:  INCBIN "gfx/menu_icons/hitmonchan.2bpp"
LickitungMenuIcon:   INCBIN "gfx/menu_icons/lickitung.2bpp"
KoffingMenuIcon:     INCBIN "gfx/menu_icons/koffing.2bpp"
WeezingMenuIcon:     INCBIN "gfx/menu_icons/weezing.2bpp"
RhyhornMenuIcon:     INCBIN "gfx/menu_icons/rhyhorn.2bpp"
RhydonMenuIcon:      INCBIN "gfx/menu_icons/rhydon.2bpp"
ChanseyMenuIcon:     INCBIN "gfx/menu_icons/chansey.2bpp"
TangelaMenuIcon:     INCBIN "gfx/menu_icons/tangela.2bpp"
KangaskhanMenuIcon:  INCBIN "gfx/menu_icons/kangaskhan.2bpp"
HorseaMenuIcon:      INCBIN "gfx/menu_icons/horsea.2bpp"
SeadraMenuIcon:      INCBIN "gfx/menu_icons/seadra.2bpp"
GoldeenMenuIcon:     INCBIN "gfx/menu_icons/goldeen.2bpp"
SeakingMenuIcon:     INCBIN "gfx/menu_icons/seaking.2bpp"
StaryuMenuIcon:      INCBIN "gfx/menu_icons/staryu.2bpp"

SECTION "Menu Icons 3", ROMX

StarmieMenuIcon:     INCBIN "gfx/menu_icons/starmie.2bpp"
MrMimeMenuIcon:      INCBIN "gfx/menu_icons/mr__mime.2bpp"
ScytherMenuIcon:     INCBIN "gfx/menu_icons/scyther.2bpp"
JynxMenuIcon:        INCBIN "gfx/menu_icons/jynx.2bpp"
ElectabuzzMenuIcon:  INCBIN "gfx/menu_icons/electabuzz.2bpp"
MagmarMenuIcon:      INCBIN "gfx/menu_icons/magmar.2bpp"
PinsirMenuIcon:      INCBIN "gfx/menu_icons/pinsir.2bpp"
TaurosMenuIcon:      INCBIN "gfx/menu_icons/tauros.2bpp"
MagikarpMenuIcon:    INCBIN "gfx/menu_icons/magikarp.2bpp"
GyaradosMenuIcon:    INCBIN "gfx/menu_icons/gyarados.2bpp"
LaprasMenuIcon:      INCBIN "gfx/menu_icons/lapras.2bpp"
DittoMenuIcon:       INCBIN "gfx/menu_icons/ditto.2bpp"
EeveeMenuIcon:       INCBIN "gfx/menu_icons/eevee.2bpp"
VaporeonMenuIcon:    INCBIN "gfx/menu_icons/vaporeon.2bpp"
JolteonMenuIcon:     INCBIN "gfx/menu_icons/jolteon.2bpp"
FlareonMenuIcon:     INCBIN "gfx/menu_icons/flareon.2bpp"
PorygonMenuIcon:     INCBIN "gfx/menu_icons/porygon.2bpp"
OmanyteMenuIcon:     INCBIN "gfx/menu_icons/omanyte.2bpp"
OmastarMenuIcon:     INCBIN "gfx/menu_icons/omastar.2bpp"
KabutoMenuIcon:      INCBIN "gfx/menu_icons/kabuto.2bpp"
KabutopsMenuIcon:    INCBIN "gfx/menu_icons/kabutops.2bpp"
AerodactylMenuIcon:  INCBIN "gfx/menu_icons/aerodactyl.2bpp"
SnorlaxMenuIcon:     INCBIN "gfx/menu_icons/snorlax.2bpp"
ArticunoMenuIcon:    INCBIN "gfx/menu_icons/articuno.2bpp"
ZapdosMenuIcon:      INCBIN "gfx/menu_icons/zapdos.2bpp"
MoltresMenuIcon:     INCBIN "gfx/menu_icons/moltres.2bpp"
DratiniMenuIcon:     INCBIN "gfx/menu_icons/dratini.2bpp"
DragonairMenuIcon:   INCBIN "gfx/menu_icons/dragonair.2bpp"
DragoniteMenuIcon:   INCBIN "gfx/menu_icons/dragonite.2bpp"
MewtwoMenuIcon:      INCBIN "gfx/menu_icons/mewtwo.2bpp"
MewMenuIcon:         INCBIN "gfx/menu_icons/mew.2bpp"
ChikoritaMenuIcon:   INCBIN "gfx/menu_icons/chikorita.2bpp"
BayleefMenuIcon:     INCBIN "gfx/menu_icons/bayleef.2bpp"
MeganiumMenuIcon:    INCBIN "gfx/menu_icons/meganium.2bpp"
CyndaquilMenuIcon:   INCBIN "gfx/menu_icons/cyndaquil.2bpp"
QuilavaMenuIcon:     INCBIN "gfx/menu_icons/quilava.2bpp"
TyphlosionMenuIcon:  INCBIN "gfx/menu_icons/typhlosion.2bpp"
TotodileMenuIcon:    INCBIN "gfx/menu_icons/totodile.2bpp"
CroconawMenuIcon:    INCBIN "gfx/menu_icons/croconaw.2bpp"
FeraligatrMenuIcon:  INCBIN "gfx/menu_icons/feraligatr.2bpp"
SentretMenuIcon:     INCBIN "gfx/menu_icons/sentret.2bpp"
FurretMenuIcon:      INCBIN "gfx/menu_icons/furret.2bpp"
HoothootMenuIcon:    INCBIN "gfx/menu_icons/hoothoot.2bpp"
NoctowlMenuIcon:     INCBIN "gfx/menu_icons/noctowl.2bpp"
LedybaMenuIcon:      INCBIN "gfx/menu_icons/ledyba.2bpp"
LedianMenuIcon:      INCBIN "gfx/menu_icons/ledian.2bpp"
SpinarakMenuIcon:    INCBIN "gfx/menu_icons/spinarak.2bpp"
AriadosMenuIcon:     INCBIN "gfx/menu_icons/ariados.2bpp"
CrobatMenuIcon:      INCBIN "gfx/menu_icons/crobat.2bpp"
ChinchouMenuIcon:    INCBIN "gfx/menu_icons/chinchou.2bpp"
LanturnMenuIcon:     INCBIN "gfx/menu_icons/lanturn.2bpp"
PichuMenuIcon:       INCBIN "gfx/menu_icons/pichu.2bpp"
CleffaMenuIcon:      INCBIN "gfx/menu_icons/cleffa.2bpp"
IgglybuffMenuIcon:   INCBIN "gfx/menu_icons/igglybuff.2bpp"
TogepiMenuIcon:      INCBIN "gfx/menu_icons/togepi.2bpp"
TogeticMenuIcon:     INCBIN "gfx/menu_icons/togetic.2bpp"
NatuMenuIcon:        INCBIN "gfx/menu_icons/natu.2bpp"
XatuMenuIcon:        INCBIN "gfx/menu_icons/xatu.2bpp"
MareepMenuIcon:      INCBIN "gfx/menu_icons/mareep.2bpp"
FlaaffyMenuIcon:     INCBIN "gfx/menu_icons/flaaffy.2bpp"

SECTION "Menu Icons 4", ROMX

AmpharosMenuIcon:    INCBIN "gfx/menu_icons/ampharos.2bpp"
BellossomMenuIcon:   INCBIN "gfx/menu_icons/bellossom.2bpp"
MarillMenuIcon:      INCBIN "gfx/menu_icons/marill.2bpp"
AzumarillMenuIcon:   INCBIN "gfx/menu_icons/azumarill.2bpp"
SudowoodoMenuIcon:   INCBIN "gfx/menu_icons/sudowoodo.2bpp"
PolitoedMenuIcon:    INCBIN "gfx/menu_icons/politoed.2bpp"
HoppipMenuIcon:      INCBIN "gfx/menu_icons/hoppip.2bpp"
SkiploomMenuIcon:    INCBIN "gfx/menu_icons/skiploom.2bpp"
JumpluffMenuIcon:    INCBIN "gfx/menu_icons/jumpluff.2bpp"
AipomMenuIcon:       INCBIN "gfx/menu_icons/aipom.2bpp"
SunkernMenuIcon:     INCBIN "gfx/menu_icons/sunkern.2bpp"
SunfloraMenuIcon:    INCBIN "gfx/menu_icons/sunflora.2bpp"
YanmaMenuIcon:       INCBIN "gfx/menu_icons/yanma.2bpp"
WooperMenuIcon:      INCBIN "gfx/menu_icons/wooper.2bpp"
QuagsireMenuIcon:    INCBIN "gfx/menu_icons/quagsire.2bpp"
EspeonMenuIcon:      INCBIN "gfx/menu_icons/espeon.2bpp"
UmbreonMenuIcon:     INCBIN "gfx/menu_icons/umbreon.2bpp"
MurkrowMenuIcon:     INCBIN "gfx/menu_icons/murkrow.2bpp"
SlowkingMenuIcon:    INCBIN "gfx/menu_icons/slowking.2bpp"
MisdreavusMenuIcon:  INCBIN "gfx/menu_icons/misdreavus.2bpp"
UnownMenuIcon:       INCBIN "gfx/menu_icons/unown.2bpp"
WobbuffetMenuIcon:   INCBIN "gfx/menu_icons/wobbuffet.2bpp"
GirafarigMenuIcon:   INCBIN "gfx/menu_icons/girafarig.2bpp"
PinecoMenuIcon:      INCBIN "gfx/menu_icons/pineco.2bpp"
ForretressMenuIcon:  INCBIN "gfx/menu_icons/forretress.2bpp"
DunsparceMenuIcon:   INCBIN "gfx/menu_icons/dunsparce.2bpp"
GligarMenuIcon:      INCBIN "gfx/menu_icons/gligar.2bpp"
SteelixMenuIcon:     INCBIN "gfx/menu_icons/steelix.2bpp"
SnubbullMenuIcon:    INCBIN "gfx/menu_icons/snubbull.2bpp"
GranbullMenuIcon:    INCBIN "gfx/menu_icons/granbull.2bpp"
QwilfishMenuIcon:    INCBIN "gfx/menu_icons/qwilfish.2bpp"
ScizorMenuIcon:      INCBIN "gfx/menu_icons/scizor.2bpp"
ShuckleMenuIcon:     INCBIN "gfx/menu_icons/shuckle.2bpp"
HeracrossMenuIcon:   INCBIN "gfx/menu_icons/heracross.2bpp"
SneaselMenuIcon:     INCBIN "gfx/menu_icons/sneasel.2bpp"
TeddiursaMenuIcon:   INCBIN "gfx/menu_icons/teddiursa.2bpp"
UrsaringMenuIcon:    INCBIN "gfx/menu_icons/ursaring.2bpp"
SlugmaMenuIcon:      INCBIN "gfx/menu_icons/slugma.2bpp"
MagcargoMenuIcon:    INCBIN "gfx/menu_icons/magcargo.2bpp"
SwinubMenuIcon:      INCBIN "gfx/menu_icons/swinub.2bpp"
PiloswineMenuIcon:   INCBIN "gfx/menu_icons/piloswine.2bpp"
CorsolaMenuIcon:     INCBIN "gfx/menu_icons/corsola.2bpp"
RemoraidMenuIcon:    INCBIN "gfx/menu_icons/remoraid.2bpp"
OctilleryMenuIcon:   INCBIN "gfx/menu_icons/octillery.2bpp"
DelibirdMenuIcon:    INCBIN "gfx/menu_icons/delibird.2bpp"
MantineMenuIcon:     INCBIN "gfx/menu_icons/mantine.2bpp"
SkarmoryMenuIcon:    INCBIN "gfx/menu_icons/skarmory.2bpp"
HoundourMenuIcon:    INCBIN "gfx/menu_icons/houndour.2bpp"
HoundoomMenuIcon:    INCBIN "gfx/menu_icons/houndoom.2bpp"
KingdraMenuIcon:     INCBIN "gfx/menu_icons/kingdra.2bpp"
PhanpyMenuIcon:      INCBIN "gfx/menu_icons/phanpy.2bpp"
DonphanMenuIcon:     INCBIN "gfx/menu_icons/donphan.2bpp"
Porygon2MenuIcon:    INCBIN "gfx/menu_icons/porygon2.2bpp"
StantlerMenuIcon:    INCBIN "gfx/menu_icons/stantler.2bpp"
SmeargleMenuIcon:    INCBIN "gfx/menu_icons/smeargle.2bpp"
TyrogueMenuIcon:     INCBIN "gfx/menu_icons/tyrogue.2bpp"
HitmontopMenuIcon:   INCBIN "gfx/menu_icons/hitmontop.2bpp"
SmoochumMenuIcon:    INCBIN "gfx/menu_icons/smoochum.2bpp"
ElekidMenuIcon:      INCBIN "gfx/menu_icons/elekid.2bpp"
MagbyMenuIcon:       INCBIN "gfx/menu_icons/magby.2bpp"

SECTION "Menu Icons 5", ROMX

MiltankMenuIcon:     INCBIN "gfx/menu_icons/miltank.2bpp"
BlisseyMenuIcon:     INCBIN "gfx/menu_icons/blissey.2bpp"
RaikouMenuIcon:      INCBIN "gfx/menu_icons/raikou.2bpp"
EnteiMenuIcon:       INCBIN "gfx/menu_icons/entei.2bpp"
SuicuneMenuIcon:     INCBIN "gfx/menu_icons/suicune.2bpp"
LarvitarMenuIcon:    INCBIN "gfx/menu_icons/larvitar.2bpp"
PupitarMenuIcon:     INCBIN "gfx/menu_icons/pupitar.2bpp"
TyranitarMenuIcon:   INCBIN "gfx/menu_icons/tyranitar.2bpp"
LugiaMenuIcon:       INCBIN "gfx/menu_icons/lugia.2bpp"
HoOhMenuIcon:        INCBIN "gfx/menu_icons/ho_oh.2bpp"
CelebiMenuIcon:      INCBIN "gfx/menu_icons/celebi.2bpp"
HonchkrowMenuIcon:   INCBIN "gfx/menu_icons/honchkrow.2bpp"
AmbipomMenuIcon:     INCBIN "gfx/menu_icons/ambipom.2bpp"
AnnihilapeMenuIcon:  INCBIN "gfx/menu_icons/annihilape.2bpp"
BagonMenuIcon:       INCBIN "gfx/menu_icons/bagon.2bpp"
DrunsparceMenuIcon:  INCBIN "gfx/menu_icons/drunsparce.2bpp"
ElectivireMenuIcon:  INCBIN "gfx/menu_icons/electivire.2bpp"
FarigirafMenuIcon:   INCBIN "gfx/menu_icons/farigiraf.2bpp"
GardevoirMenuIcon:   INCBIN "gfx/menu_icons/gardevoir.2bpp"
GlaceonMenuIcon:     INCBIN "gfx/menu_icons/glaceon.2bpp"
GliscorMenuIcon:     INCBIN "gfx/menu_icons/gliscor.2bpp"
KirliaMenuIcon:      INCBIN "gfx/menu_icons/kirlia.2bpp"
LeafeonMenuIcon:     INCBIN "gfx/menu_icons/leafeon.2bpp"
LickilickyMenuIcon:  INCBIN "gfx/menu_icons/lickilicky.2bpp"
MagmortarMenuIcon:   INCBIN "gfx/menu_icons/magmortar.2bpp"
MagnezoneMenuIcon:   INCBIN "gfx/menu_icons/magnezone.2bpp"
MamoswineMenuIcon:   INCBIN "gfx/menu_icons/mamoswine.2bpp"
MesmeriaMenuIcon:    INCBIN "gfx/menu_icons/mesmeria.2bpp"
MismagiusMenuIcon:   INCBIN "gfx/menu_icons/mismagius.2bpp"
PorygonZMenuIcon:    INCBIN "gfx/menu_icons/porygon_z.2bpp"
RaltsMenuIcon:       INCBIN "gfx/menu_icons/ralts.2bpp"
RhyperiorMenuIcon:   INCBIN "gfx/menu_icons/rhyperior.2bpp"
SalamenceMenuIcon:   INCBIN "gfx/menu_icons/salamence.2bpp"
ScolipedeMenuIcon:   INCBIN "gfx/menu_icons/scolipede.2bpp"
ShelgonMenuIcon:     INCBIN "gfx/menu_icons/shelgon.2bpp"
TangrowthMenuIcon:   INCBIN "gfx/menu_icons/tangrowth.2bpp"
TogekissMenuIcon:    INCBIN "gfx/menu_icons/togekiss.2bpp"
UrsalunaMenuIcon:    INCBIN "gfx/menu_icons/ursaluna.2bpp"
VenipedeMenuIcon:    INCBIN "gfx/menu_icons/venipede.2bpp"
WeavileMenuIcon:     INCBIN "gfx/menu_icons/weavile.2bpp"
WhirlipedeMenuIcon:  INCBIN "gfx/menu_icons/whirlipede.2bpp"
WyrdeerMenuIcon:     INCBIN "gfx/menu_icons/wyrdeer.2bpp"
YanmegaMenuIcon:     INCBIN "gfx/menu_icons/yanmega.2bpp"
LileepMenuIcon:      INCBIN "gfx/menu_icons/lileep.2bpp"
CradilyMenuIcon:     INCBIN "gfx/menu_icons/cradily.2bpp"
ArmaldoMenuIcon:     INCBIN "gfx/menu_icons/armaldo.2bpp"
GolettMenuIcon:      INCBIN "gfx/menu_icons/golett.2bpp"
GolurkMenuIcon:      INCBIN "gfx/menu_icons/golurk.2bpp"
DuskullMenuIcon:     INCBIN "gfx/menu_icons/duskull.2bpp"
DusclopsMenuIcon:    INCBIN "gfx/menu_icons/dusclops.2bpp"
DusknoirMenuIcon:    INCBIN "gfx/menu_icons/dusknoir.2bpp"
TimburrMenuIcon:     INCBIN "gfx/menu_icons/fighter.2bpp" ; TODO: gfx/menu_icons/timburr.png
GurdurrMenuIcon:     INCBIN "gfx/menu_icons/fighter.2bpp" ; TODO: gfx/menu_icons/gurdurr.png
ConkeldurrMenuIcon:  INCBIN "gfx/menu_icons/fighter.2bpp" ; TODO: gfx/menu_icons/conkeldurr.png
LarvestaMenuIcon:    INCBIN "gfx/menu_icons/caterpillar.2bpp" ; TODO: gfx/menu_icons/larvesta.png
VolcaronaMenuIcon:   INCBIN "gfx/menu_icons/moth.2bpp" ; TODO: gfx/menu_icons/volcarona.png
DeinoMenuIcon:       INCBIN "gfx/menu_icons/deino.2bpp"
ZweilousMenuIcon:    INCBIN "gfx/menu_icons/zweilous.2bpp"
HydreigonMenuIcon:   INCBIN "gfx/menu_icons/hydreigon.2bpp"
DreepyMenuIcon:      INCBIN "gfx/menu_icons/ghost.2bpp" ; TODO: gfx/menu_icons/dreepy.png
DrakloakMenuIcon:    INCBIN "gfx/menu_icons/drakloak.2bpp"
DragapultMenuIcon:   INCBIN "gfx/menu_icons/dragapult.2bpp"
ImpidimpMenuIcon:    INCBIN "gfx/menu_icons/monster.2bpp" ; TODO: gfx/menu_icons/impidimp.png
MorgremMenuIcon:     INCBIN "gfx/menu_icons/monster.2bpp" ; TODO: gfx/menu_icons/morgrem.png
GrimmsnarlMenuIcon:  INCBIN "gfx/menu_icons/monster.2bpp" ; TODO: gfx/menu_icons/grimmsnarl.png
TinkatinkMenuIcon:   INCBIN "gfx/menu_icons/tinkatink.2bpp"
TinkatuffMenuIcon:   INCBIN "gfx/menu_icons/tinkatuff.2bpp"
TinkatonMenuIcon:    INCBIN "gfx/menu_icons/tinkaton.2bpp"
FrigibaxMenuIcon:    INCBIN "gfx/menu_icons/frigibax.2bpp"
ArctibaxMenuIcon:    INCBIN "gfx/menu_icons/arctibax.2bpp"
BaxcaliburMenuIcon:  INCBIN "gfx/menu_icons/baxcalibur.2bpp"
CharcadetMenuIcon:   INCBIN "gfx/menu_icons/charcadet.2bpp"
ArmarougeMenuIcon:   INCBIN "gfx/menu_icons/armarouge.2bpp"
CeruledgeMenuIcon:   INCBIN "gfx/menu_icons/ceruledge.2bpp"
SylveonMenuIcon:     INCBIN "gfx/menu_icons/sylveon.2bpp"
RookideeMenuIcon:    INCBIN "gfx/menu_icons/rookidee.2bpp"
CorvisquireMenuIcon: INCBIN "gfx/menu_icons/corvisquire.2bpp"
CorviknightMenuIcon: INCBIN "gfx/menu_icons/corviknight.2bpp"
SECTION "Menu Icons 5b", ROMX

AbomasnowMenuIcon:   INCBIN "gfx/menu_icons/monster.2bpp" ; TODO: gfx/menu_icons/abomasnow.png
AltariaMenuIcon:     INCBIN "gfx/menu_icons/altaria.2bpp"
AnorithMenuIcon:     INCBIN "gfx/menu_icons/anorith.2bpp"
AppletunMenuIcon:    INCBIN "gfx/menu_icons/appletun.2bpp"
ApplinMenuIcon:      INCBIN "gfx/menu_icons/applin.2bpp"
ArchaludonMenuIcon:  INCBIN "gfx/menu_icons/archaludon.2bpp"
BreloomMenuIcon:     INCBIN "gfx/menu_icons/breloom.2bpp"
BunearyMenuIcon:     INCBIN "gfx/menu_icons/buneary.2bpp"
CameruptMenuIcon:    INCBIN "gfx/menu_icons/camerupt.2bpp"
CentiskorchMenuIcon: INCBIN "gfx/menu_icons/centiskorch.2bpp"
CharjabugMenuIcon:   INCBIN "gfx/menu_icons/bug.2bpp" ; TODO: gfx/menu_icons/charjabug.png
CroagunkMenuIcon:    INCBIN "gfx/menu_icons/croagunk.2bpp"
DipplinMenuIcon:     INCBIN "gfx/menu_icons/dipplin.2bpp"
DrifblimMenuIcon:    INCBIN "gfx/menu_icons/drifblim.2bpp"
DrifloonMenuIcon:    INCBIN "gfx/menu_icons/drifloon.2bpp"
DrilburMenuIcon:     INCBIN "gfx/menu_icons/drilbur.2bpp"
DuraludonMenuIcon:   INCBIN "gfx/menu_icons/monster.2bpp" ; TODO: gfx/menu_icons/duraludon.png
ElectrikeMenuIcon:   INCBIN "gfx/menu_icons/electrike.2bpp"
ExcadrillMenuIcon:   INCBIN "gfx/menu_icons/excadrill.2bpp"
FlappleMenuIcon:     INCBIN "gfx/menu_icons/flapple.2bpp"
FletchinderMenuIcon: INCBIN "gfx/menu_icons/bird.2bpp" ; TODO: gfx/menu_icons/fletchinder.png
FletchlingMenuIcon:  INCBIN "gfx/menu_icons/bird.2bpp" ; TODO: gfx/menu_icons/fletchling.png
FlygonMenuIcon:      INCBIN "gfx/menu_icons/flygon.2bpp"
FroslassMenuIcon:    INCBIN "gfx/menu_icons/froslass.2bpp"
GolisopodMenuIcon:   INCBIN "gfx/menu_icons/golisopod.2bpp"
GrubbinMenuIcon:     INCBIN "gfx/menu_icons/bug.2bpp" ; TODO: gfx/menu_icons/grubbin.png
GrumpigMenuIcon:     INCBIN "gfx/menu_icons/quadruped.2bpp" ; TODO: gfx/menu_icons/grumpig.png
HydrappleMenuIcon:   INCBIN "gfx/menu_icons/hydrapple.2bpp"
KingambitMenuIcon:   INCBIN "gfx/menu_icons/kingambit.2bpp"
LombreMenuIcon:      INCBIN "gfx/menu_icons/lombre.2bpp"
LopunnyMenuIcon:     INCBIN "gfx/menu_icons/lopunny.2bpp"
LotadMenuIcon:       INCBIN "gfx/menu_icons/lotad.2bpp"
LudicoloMenuIcon:    INCBIN "gfx/menu_icons/ludicolo.2bpp"
ManectricMenuIcon:   INCBIN "gfx/menu_icons/manectric.2bpp"
NumelMenuIcon:       INCBIN "gfx/menu_icons/numel.2bpp"
OverqwilMenuIcon:    INCBIN "gfx/menu_icons/overqwil.2bpp"
ScraftyMenuIcon:     INCBIN "gfx/menu_icons/scrafty.2bpp"
ScraggyMenuIcon:     INCBIN "gfx/menu_icons/scraggy.2bpp"
SealeoMenuIcon:      INCBIN "gfx/menu_icons/seel.2bpp" ; TODO: gfx/menu_icons/sealeo.png
ShroomishMenuIcon:   INCBIN "gfx/menu_icons/shroomish.2bpp"
SizzlipedeMenuIcon:  INCBIN "gfx/menu_icons/sizzlipede.2bpp"
SnoruntMenuIcon:     INCBIN "gfx/menu_icons/snorunt.2bpp"
SnoverMenuIcon:      INCBIN "gfx/menu_icons/plant.2bpp" ; TODO: gfx/menu_icons/snover.png
SphealMenuIcon:      INCBIN "gfx/menu_icons/seel.2bpp" ; TODO: gfx/menu_icons/spheal.png
SpoinkMenuIcon:      INCBIN "gfx/menu_icons/quadruped.2bpp" ; TODO: gfx/menu_icons/spoink.png
SwabluMenuIcon:      INCBIN "gfx/menu_icons/swablu.2bpp"
TalonflameMenuIcon:  INCBIN "gfx/menu_icons/bird.2bpp" ; TODO: gfx/menu_icons/talonflame.png
ToxicroakMenuIcon:   INCBIN "gfx/menu_icons/toxicroak.2bpp"
TrapinchMenuIcon:    INCBIN "gfx/menu_icons/trapinch.2bpp"
UrsalunabmMenuIcon:  INCBIN "gfx/menu_icons/ursaluna_bloodmoon.2bpp"
VibravaMenuIcon:     INCBIN "gfx/menu_icons/vibrava.2bpp"
VikavoltMenuIcon:    INCBIN "gfx/menu_icons/bug.2bpp" ; TODO: gfx/menu_icons/vikavolt.png
WalreinMenuIcon:     INCBIN "gfx/menu_icons/dewgong.2bpp" ; TODO: gfx/menu_icons/walrein.png
WimpodMenuIcon:      INCBIN "gfx/menu_icons/wimpod.2bpp"
TeddiursabmMenuIcon: INCBIN "gfx/menu_icons/teddiursa.2bpp"
UrsaringbmMenuIcon:  INCBIN "gfx/menu_icons/ursaring.2bpp"

SECTION "Menu Icons 6", ROMX

AxewMenuIcon:        INCBIN "gfx/menu_icons/axew.2bpp"
FraxureMenuIcon:     INCBIN "gfx/menu_icons/fraxure.2bpp"
HaxorusMenuIcon:     INCBIN "gfx/menu_icons/haxorus.2bpp"
CranidosMenuIcon:    INCBIN "gfx/menu_icons/cranidos.2bpp"
RampardosMenuIcon:   INCBIN "gfx/menu_icons/rampardos.2bpp"
ShieldonMenuIcon:    INCBIN "gfx/menu_icons/shieldon.2bpp"
BastiodonMenuIcon:   INCBIN "gfx/menu_icons/bastiodon.2bpp"
PawniardMenuIcon:    INCBIN "gfx/menu_icons/pawniard.2bpp"
BisharpMenuIcon:     INCBIN "gfx/menu_icons/bisharp.2bpp"
MimikyuMenuIcon:     INCBIN "gfx/menu_icons/mimikyu.2bpp"
CursolaMenuIcon:     INCBIN "gfx/menu_icons/cursola.2bpp"
MrRimeMenuIcon:      INCBIN "gfx/menu_icons/mr__rime.2bpp"
SirfetchDMenuIcon:   INCBIN "gfx/menu_icons/sirfetch_d.2bpp"
RioluMenuIcon:       INCBIN "gfx/menu_icons/riolu.2bpp"
LucarioMenuIcon:     INCBIN "gfx/menu_icons/lucario.2bpp"
TyruntMenuIcon:      INCBIN "gfx/menu_icons/tyrunt.2bpp"
TyrantrumMenuIcon:   INCBIN "gfx/menu_icons/tyrantrum.2bpp"
AmauraMenuIcon:      INCBIN "gfx/menu_icons/amaura.2bpp"
AurorusMenuIcon:     INCBIN "gfx/menu_icons/aurorus.2bpp"
MunchlaxMenuIcon:    INCBIN "gfx/menu_icons/munchlax.2bpp"
OrstryxMenuIcon:     INCBIN "gfx/menu_icons/noctowl.2bpp"

SECTION "Menu Icons 7", ROMX

RattataAlolanMenuIcon: INCBIN "gfx/menu_icons/rattata_alolan.2bpp"
RaticateAlolanMenuIcon: INCBIN "gfx/menu_icons/raticate_alolan.2bpp"
RaichuAlolanMenuIcon: INCBIN "gfx/menu_icons/raichu_alolan.2bpp"
SandshrewAlolanMenuIcon: INCBIN "gfx/menu_icons/sandshrew_alolan.2bpp"
SandslashAlolanMenuIcon: INCBIN "gfx/menu_icons/sandslash_alolan.2bpp"
VulpixAlolanMenuIcon: INCBIN "gfx/menu_icons/vulpix_alolan.2bpp"
NinetalesAlolanMenuIcon: INCBIN "gfx/menu_icons/ninetales_alolan.2bpp"
DiglettAlolanMenuIcon: INCBIN "gfx/menu_icons/diglett_alolan.2bpp"
DugtrioAlolanMenuIcon: INCBIN "gfx/menu_icons/dugtrio_alolan.2bpp"
MeowthAlolanMenuIcon: INCBIN "gfx/menu_icons/meowth_alolan.2bpp"
PersianAlolanMenuIcon: INCBIN "gfx/menu_icons/persian_alolan.2bpp"
GeodudeAlolanMenuIcon: INCBIN "gfx/menu_icons/geodude_alolan.2bpp"
GravelerAlolanMenuIcon: INCBIN "gfx/menu_icons/graveler_alolan.2bpp"
GolemAlolanMenuIcon: INCBIN "gfx/menu_icons/golem_alolan.2bpp"
GrimerAlolanMenuIcon: INCBIN "gfx/menu_icons/grimer_alolan.2bpp"
MukAlolanMenuIcon: INCBIN "gfx/menu_icons/muk_alolan.2bpp"
ExeggutorAlolanMenuIcon: INCBIN "gfx/menu_icons/exeggutor_alolan.2bpp"
MarowakAlolanMenuIcon: INCBIN "gfx/menu_icons/marowak_alolan.2bpp"
MeowthGalarianMenuIcon: INCBIN "gfx/menu_icons/meowth_galarian.2bpp"
PerrserkerMenuIcon: INCBIN "gfx/menu_icons/perrserker.2bpp"
PonytaGalarianMenuIcon: INCBIN "gfx/menu_icons/ponyta_galarian.2bpp"
RapidashGalarianMenuIcon: INCBIN "gfx/menu_icons/rapidash_galarian.2bpp"
SlowpokeGalarianMenuIcon: INCBIN "gfx/menu_icons/slowpoke_galarian.2bpp"
SlowbroGalarianMenuIcon: INCBIN "gfx/menu_icons/slowbro_galarian.2bpp"
WeezingGalarianMenuIcon: INCBIN "gfx/menu_icons/weezing_galarian.2bpp"
SlowkingGalarianMenuIcon: INCBIN "gfx/menu_icons/slowking_galarian.2bpp"
CorsolaGalarianMenuIcon: INCBIN "gfx/menu_icons/corsola_galarian.2bpp"
GrowlitheHisuianMenuIcon: INCBIN "gfx/menu_icons/growlithe_hisuian.2bpp"
ArcanineHisuianMenuIcon: INCBIN "gfx/menu_icons/arcanine_hisuian.2bpp"
VoltorbHisuianMenuIcon: INCBIN "gfx/menu_icons/voltorb_hisuian.2bpp"
ElectrodeHisuianMenuIcon: INCBIN "gfx/menu_icons/electrode_hisuian.2bpp"
TyphlosionHisuianMenuIcon: INCBIN "gfx/menu_icons/typhlosion_hisuian.2bpp"
SneaselHisuianMenuIcon: INCBIN "gfx/menu_icons/sneasel_hisuian.2bpp"
WooperPaldeanMenuIcon: INCBIN "gfx/menu_icons/wooper_paldean.2bpp"
ClodsireMenuIcon: INCBIN "gfx/menu_icons/clodsire.2bpp"
TaurosPaldeanFireMenuIcon: INCBIN "gfx/menu_icons/tauros_paldean_fire.2bpp"
TaurosPaldeanWaterMenuIcon: INCBIN "gfx/menu_icons/tauros_paldean_water.2bpp"
SneaslerMenuIcon: INCBIN "gfx/menu_icons/sneasler.2bpp"
WatuMenuIcon: INCBIN "gfx/menu_icons/bird.2bpp" ; TODO: gfx/menu_icons/watu.png
BounsweetMenuIcon: INCBIN "gfx/menu_icons/oddish.2bpp" ; TODO: gfx/menu_icons/bounsweet.png
SteeneeMenuIcon: INCBIN "gfx/menu_icons/oddish.2bpp" ; TODO: gfx/menu_icons/steenee.png
TsareenaMenuIcon: INCBIN "gfx/menu_icons/humanshape.2bpp" ; TODO: gfx/menu_icons/tsareena.png
AronMenuIcon: INCBIN "gfx/menu_icons/aron.2bpp"
LaironMenuIcon: INCBIN "gfx/menu_icons/lairon.2bpp"
AggronMenuIcon: INCBIN "gfx/menu_icons/aggron.2bpp"
KleavorMenuIcon: INCBIN "gfx/menu_icons/kleavor.2bpp"
GlimmetMenuIcon: INCBIN "gfx/menu_icons/glimmet.2bpp"
MareanieMenuIcon: INCBIN "gfx/menu_icons/jellyfish.2bpp" ; TODO: gfx/menu_icons/mareanie.png
ToxapexMenuIcon: INCBIN "gfx/menu_icons/jellyfish.2bpp" ; TODO: gfx/menu_icons/toxapex.png
ZangooseMenuIcon: INCBIN "gfx/menu_icons/monster.2bpp" ; TODO: gfx/menu_icons/zangoose.png
SeviperMenuIcon: INCBIN "gfx/menu_icons/serpent.2bpp" ; TODO: gfx/menu_icons/seviper.png
GlimmoraMenuIcon: INCBIN "gfx/menu_icons/glimmora.2bpp"
CetoddleMenuIcon: INCBIN "gfx/menu_icons/cetoddle.2bpp"
CetitanMenuIcon: INCBIN "gfx/menu_icons/cetitan.2bpp"

EggMenuIcon:         INCBIN "gfx/menu_icons/egg.2bpp"
